[server]
listener_addr = "0.0.0.0:8080"
log_level = "INFO"

[attestor]
attestor_query_timeout_ms = 5000
quorum_threshold = 2
attestor_endpoints = [
    "http://ibc-attestor-1:9000",
    "http://ibc-attestor-2:9001",
    "http://ibc-attestor-3:9002",
]
