// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proofapi/proofapi.proto

package proofapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProofApiService_RelayByTx_FullMethodName    = "/proofapi.ProofApiService/RelayByTx"
	ProofApiService_CreateClient_FullMethodName = "/proofapi.ProofApiService/CreateClient"
	ProofApiService_UpdateClient_FullMethodName = "/proofapi.ProofApiService/UpdateClient"
	ProofApiService_Info_FullMethodName         = "/proofapi.ProofApiService/Info"
)

// ProofApiServiceClient is the client API for ProofApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The proof API service definition.
// Each proof API service is defined between two chains.
// One chain is the source chain, and the other chain is the target chain.
type ProofApiServiceClient interface {
	// Relay the ibc packets produced by the results of transactions
	RelayByTx(ctx context.Context, in *RelayByTxRequest, opts ...grpc.CallOption) (*RelayByTxResponse, error)
	// Create a new ibc client on the target (destination) chain
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	// Update the ibc client on the target (destination) chain
	UpdateClient(ctx context.Context, in *UpdateClientRequest, opts ...grpc.CallOption) (*UpdateClientResponse, error)
	// Request proof API information
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type proofApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProofApiServiceClient(cc grpc.ClientConnInterface) ProofApiServiceClient {
	return &proofApiServiceClient{cc}
}

func (c *proofApiServiceClient) RelayByTx(ctx context.Context, in *RelayByTxRequest, opts ...grpc.CallOption) (*RelayByTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayByTxResponse)
	err := c.cc.Invoke(ctx, ProofApiService_RelayByTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proofApiServiceClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, ProofApiService_CreateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proofApiServiceClient) UpdateClient(ctx context.Context, in *UpdateClientRequest, opts ...grpc.CallOption) (*UpdateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateClientResponse)
	err := c.cc.Invoke(ctx, ProofApiService_UpdateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proofApiServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, ProofApiService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProofApiServiceServer is the server API for ProofApiService service.
// All implementations must embed UnimplementedProofApiServiceServer
// for forward compatibility.
//
// The proof API service definition.
// Each proof API service is defined between two chains.
// One chain is the source chain, and the other chain is the target chain.
type ProofApiServiceServer interface {
	// Relay the ibc packets produced by the results of transactions
	RelayByTx(context.Context, *RelayByTxRequest) (*RelayByTxResponse, error)
	// Create a new ibc client on the target (destination) chain
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	// Update the ibc client on the target (destination) chain
	UpdateClient(context.Context, *UpdateClientRequest) (*UpdateClientResponse, error)
	// Request proof API information
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	mustEmbedUnimplementedProofApiServiceServer()
}

// UnimplementedProofApiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProofApiServiceServer struct{}

func (UnimplementedProofApiServiceServer) RelayByTx(context.Context, *RelayByTxRequest) (*RelayByTxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayByTx not implemented")
}
func (UnimplementedProofApiServiceServer) CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClient not implemented")
}
func (UnimplementedProofApiServiceServer) UpdateClient(context.Context, *UpdateClientRequest) (*UpdateClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateClient not implemented")
}
func (UnimplementedProofApiServiceServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedProofApiServiceServer) mustEmbedUnimplementedProofApiServiceServer() {}
func (UnimplementedProofApiServiceServer) testEmbeddedByValue()                         {}

// UnsafeProofApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProofApiServiceServer will
// result in compilation errors.
type UnsafeProofApiServiceServer interface {
	mustEmbedUnimplementedProofApiServiceServer()
}

func RegisterProofApiServiceServer(s grpc.ServiceRegistrar, srv ProofApiServiceServer) {
	// If the following call panics, it indicates UnimplementedProofApiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProofApiService_ServiceDesc, srv)
}

func _ProofApiService_RelayByTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayByTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProofApiServiceServer).RelayByTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProofApiService_RelayByTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProofApiServiceServer).RelayByTx(ctx, req.(*RelayByTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProofApiService_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProofApiServiceServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProofApiService_CreateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProofApiServiceServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProofApiService_UpdateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProofApiServiceServer).UpdateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProofApiService_UpdateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProofApiServiceServer).UpdateClient(ctx, req.(*UpdateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProofApiService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProofApiServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProofApiService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProofApiServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProofApiService_ServiceDesc is the grpc.ServiceDesc for ProofApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProofApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proofapi.ProofApiService",
	HandlerType: (*ProofApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RelayByTx",
			Handler:    _ProofApiService_RelayByTx_Handler,
		},
		{
			MethodName: "CreateClient",
			Handler:    _ProofApiService_CreateClient_Handler,
		},
		{
			MethodName: "UpdateClient",
			Handler:    _ProofApiService_UpdateClient_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _ProofApiService_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proofapi/proofapi.proto",
}
