// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package dummy_ibc_app

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_DummyIbcAppInstructionsSendPacketPacketSent:
		value := new(DummyIbcAppInstructionsSendPacketPacketSent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as DummyIbcAppInstructionsSendPacketPacketSent: %w", err)
		}
		return value, nil
	case Event_DummyIbcAppStatePacketAcknowledged:
		value := new(DummyIbcAppStatePacketAcknowledged)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as DummyIbcAppStatePacketAcknowledged: %w", err)
		}
		return value, nil
	case Event_DummyIbcAppStatePacketReceived:
		value := new(DummyIbcAppStatePacketReceived)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as DummyIbcAppStatePacketReceived: %w", err)
		}
		return value, nil
	case Event_DummyIbcAppStatePacketTimedOut:
		value := new(DummyIbcAppStatePacketTimedOut)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as DummyIbcAppStatePacketTimedOut: %w", err)
		}
		return value, nil
	case Event_DummyIbcAppStateTransferSent:
		value := new(DummyIbcAppStateTransferSent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as DummyIbcAppStateTransferSent: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_DummyIbcAppInstructionsSendPacketPacketSent(eventData []byte) (*DummyIbcAppInstructionsSendPacketPacketSent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_DummyIbcAppInstructionsSendPacketPacketSent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_DummyIbcAppInstructionsSendPacketPacketSent, binary.FormatDiscriminator(discriminator))
	}
	event := new(DummyIbcAppInstructionsSendPacketPacketSent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type DummyIbcAppInstructionsSendPacketPacketSent: %w", err)
	}
	return event, nil
}

func ParseEvent_DummyIbcAppStatePacketAcknowledged(eventData []byte) (*DummyIbcAppStatePacketAcknowledged, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_DummyIbcAppStatePacketAcknowledged {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_DummyIbcAppStatePacketAcknowledged, binary.FormatDiscriminator(discriminator))
	}
	event := new(DummyIbcAppStatePacketAcknowledged)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type DummyIbcAppStatePacketAcknowledged: %w", err)
	}
	return event, nil
}

func ParseEvent_DummyIbcAppStatePacketReceived(eventData []byte) (*DummyIbcAppStatePacketReceived, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_DummyIbcAppStatePacketReceived {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_DummyIbcAppStatePacketReceived, binary.FormatDiscriminator(discriminator))
	}
	event := new(DummyIbcAppStatePacketReceived)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type DummyIbcAppStatePacketReceived: %w", err)
	}
	return event, nil
}

func ParseEvent_DummyIbcAppStatePacketTimedOut(eventData []byte) (*DummyIbcAppStatePacketTimedOut, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_DummyIbcAppStatePacketTimedOut {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_DummyIbcAppStatePacketTimedOut, binary.FormatDiscriminator(discriminator))
	}
	event := new(DummyIbcAppStatePacketTimedOut)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type DummyIbcAppStatePacketTimedOut: %w", err)
	}
	return event, nil
}

func ParseEvent_DummyIbcAppStateTransferSent(eventData []byte) (*DummyIbcAppStateTransferSent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_DummyIbcAppStateTransferSent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_DummyIbcAppStateTransferSent, binary.FormatDiscriminator(discriminator))
	}
	event := new(DummyIbcAppStateTransferSent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type DummyIbcAppStateTransferSent: %w", err)
	}
	return event, nil
}
