// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package dummy_ibc_app

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("EkBUtUFt9rQaLeeqRk6rF7RmVmWpZ4k4CTEPsWz8t1Wn")
