version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unused
  settings:
    dogsled:
      max-blank-identifiers: 3
    revive:
      rules:
        - name: if-return
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - staticcheck
        text: 'SA1019:'
      - linters:
          - gosec
        text: Use of weak random number generator
      - linters:
          - staticcheck
        text: 'ST1003:'
      - linters:
          - staticcheck
        text: 'ST1016:'
      - linters:
          - gosec
        text: 'G115:'
      - linters:
          - gosec
        text: 'G204:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(github.com/ethereum/go-ethereum)
        - prefix(cosmossdk.io)
        - prefix(github.com/cosmos/cosmos-sdk)
        - prefix(github.com/cometbft/cometbft)
        - prefix(github.com/cosmos/ibc-go)
        - prefix(github.com/CosmWasm/wasmd)
        - prefix(github.com/strangelove-ventures/interchaintest)
        - prefix(github.com/cosmos/solidity-ibc-eureka/packages/go-abigen)
        - prefix(github.com/srdtrk/solidity-ibc-eureka/e2e/v8)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
