// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: gmp/packet.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GMPPacketData defines a struct for the packet payload
type GMPPacketData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the sender address
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// the recipient address on the destination chain
	Receiver string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// The salt used to generate the caller account address
	Salt []byte `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	// The payload of the call
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// optional memo
	Memo          string `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GMPPacketData) Reset() {
	*x = GMPPacketData{}
	mi := &file_gmp_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GMPPacketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMPPacketData) ProtoMessage() {}

func (x *GMPPacketData) ProtoReflect() protoreflect.Message {
	mi := &file_gmp_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMPPacketData.ProtoReflect.Descriptor instead.
func (*GMPPacketData) Descriptor() ([]byte, []int) {
	return file_gmp_packet_proto_rawDescGZIP(), []int{0}
}

func (x *GMPPacketData) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *GMPPacketData) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *GMPPacketData) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *GMPPacketData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GMPPacketData) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

// Acknowledgement defines a struct for the ICS27-2 acknowledgement
type Acknowledgement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The result of the call
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_gmp_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_gmp_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_gmp_packet_proto_rawDescGZIP(), []int{1}
}

func (x *Acknowledgement) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_gmp_packet_proto protoreflect.FileDescriptor

const file_gmp_packet_proto_rawDesc = "" +
	"\n" +
	"\x10gmp/packet.proto\x12\x17ibc.applications.gmp.v1\"\x85\x01\n" +
	"\rGMPPacketData\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\tR\breceiver\x12\x12\n" +
	"\x04salt\x18\x03 \x01(\fR\x04salt\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x12\n" +
	"\x04memo\x18\x05 \x01(\tR\x04memo\")\n" +
	"\x0fAcknowledgement\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06resultB\xe1\x01\n" +
	"\x1bcom.ibc.applications.gmp.v1B\vPacketProtoP\x01Z6github.com/cosmos/ibc-go/v10/modules/apps/27-gmp/types\xa2\x02\x03IAG\xaa\x02\x17Ibc.Applications.Gmp.V1\xca\x02\x17Ibc\\Applications\\Gmp\\V1\xe2\x02#Ibc\\Applications\\Gmp\\V1\\GPBMetadata\xea\x02\x1aIbc::Applications::Gmp::V1b\x06proto3"

var (
	file_gmp_packet_proto_rawDescOnce sync.Once
	file_gmp_packet_proto_rawDescData []byte
)

func file_gmp_packet_proto_rawDescGZIP() []byte {
	file_gmp_packet_proto_rawDescOnce.Do(func() {
		file_gmp_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gmp_packet_proto_rawDesc), len(file_gmp_packet_proto_rawDesc)))
	})
	return file_gmp_packet_proto_rawDescData
}

var file_gmp_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gmp_packet_proto_goTypes = []any{
	(*GMPPacketData)(nil),   // 0: ibc.applications.gmp.v1.GMPPacketData
	(*Acknowledgement)(nil), // 1: ibc.applications.gmp.v1.Acknowledgement
}
var file_gmp_packet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gmp_packet_proto_init() }
func file_gmp_packet_proto_init() {
	if File_gmp_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gmp_packet_proto_rawDesc), len(file_gmp_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gmp_packet_proto_goTypes,
		DependencyIndexes: file_gmp_packet_proto_depIdxs,
		MessageInfos:      file_gmp_packet_proto_msgTypes,
	}.Build()
	File_gmp_packet_proto = out.File
	file_gmp_packet_proto_goTypes = nil
	file_gmp_packet_proto_depIdxs = nil
}
