name: e2e-build

inputs:
  github_token:
    description: A Github PAT
    required: true

runs:
  using: composite
  steps:
    - name: Set up foundry tooling
      uses: ./.github/actions/foundry-setup

    - name: Install SP1 toolchain
      shell: bash
      run: |
        curl -L https://sp1.succinct.xyz | bash
        ~/.sp1/bin/sp1up --token ${{ inputs.github_token }}
        ~/.sp1/bin/cargo-prove prove --version

    - name: Install just
      uses: extractions/setup-just@v2

    - name: Build SP1 Programs
      shell: bash
      run: just build-sp1-programs

    - name: Install operator
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --bin operator --path programs/operator --locked

    - name: Install relayer
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --bin relayer --path programs/relayer --locked

    - name: Package artifacts
      shell: bash
      run: |
        mkdir -p e2e-artifacts/bin
        mkdir -p e2e-artifacts/sp1-programs
        cp ~/.cargo/bin/relayer e2e-artifacts/bin/
        cp ~/.cargo/bin/operator e2e-artifacts/bin/
        cp -r programs/sp1-programs/target/elf-compilation/riscv32im-succinct-zkvm-elf/release/* e2e-artifacts/sp1-programs/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: e2e-build-artifacts
        path: e2e-artifacts/
        retention-days: 1
