// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package attestation_light_client

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Parameters for update_client instruction
type AttestationLightClientInstructionsUpdateClientUpdateClientParams struct {
	Proof []byte `json:"proof"`
}

func (obj AttestationLightClientInstructionsUpdateClientUpdateClientParams) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Proof`:
	err = encoder.Encode(obj.Proof)
	if err != nil {
		return errors.NewField("Proof", err)
	}
	return nil
}

func (obj AttestationLightClientInstructionsUpdateClientUpdateClientParams) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AttestationLightClientInstructionsUpdateClientUpdateClientParams: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AttestationLightClientInstructionsUpdateClientUpdateClientParams) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Proof`:
	err = decoder.Decode(&obj.Proof)
	if err != nil {
		return errors.NewField("Proof", err)
	}
	return nil
}

func (obj *AttestationLightClientInstructionsUpdateClientUpdateClientParams) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AttestationLightClientInstructionsUpdateClientUpdateClientParams: %w", err)
	}
	return nil
}

func UnmarshalAttestationLightClientInstructionsUpdateClientUpdateClientParams(buf []byte) (*AttestationLightClientInstructionsUpdateClientUpdateClientParams, error) {
	obj := new(AttestationLightClientInstructionsUpdateClientUpdateClientParams)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Storage for consensus state at a specific height
type AttestationLightClientStateConsensusStateStore struct {
	Height         uint64                                    `json:"height"`
	ConsensusState AttestationLightClientTypesConsensusState `json:"consensusState"`
}

func (obj AttestationLightClientStateConsensusStateStore) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Height`:
	err = encoder.Encode(obj.Height)
	if err != nil {
		return errors.NewField("Height", err)
	}
	// Serialize `ConsensusState`:
	err = encoder.Encode(obj.ConsensusState)
	if err != nil {
		return errors.NewField("ConsensusState", err)
	}
	return nil
}

func (obj AttestationLightClientStateConsensusStateStore) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AttestationLightClientStateConsensusStateStore: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AttestationLightClientStateConsensusStateStore) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Height`:
	err = decoder.Decode(&obj.Height)
	if err != nil {
		return errors.NewField("Height", err)
	}
	// Deserialize `ConsensusState`:
	err = decoder.Decode(&obj.ConsensusState)
	if err != nil {
		return errors.NewField("ConsensusState", err)
	}
	return nil
}

func (obj *AttestationLightClientStateConsensusStateStore) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AttestationLightClientStateConsensusStateStore: %w", err)
	}
	return nil
}

func UnmarshalAttestationLightClientStateConsensusStateStore(buf []byte) (*AttestationLightClientStateConsensusStateStore, error) {
	obj := new(AttestationLightClientStateConsensusStateStore)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// App state for access control
type AttestationLightClientTypesAppState struct {
	AccessManager solanago.PublicKey `json:"accessManager"`
	Reserved      [256]uint8         `json:"reserved"`
}

func (obj AttestationLightClientTypesAppState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `AccessManager`:
	err = encoder.Encode(obj.AccessManager)
	if err != nil {
		return errors.NewField("AccessManager", err)
	}
	// Serialize `Reserved`:
	err = encoder.Encode(obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj AttestationLightClientTypesAppState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AttestationLightClientTypesAppState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AttestationLightClientTypesAppState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `AccessManager`:
	err = decoder.Decode(&obj.AccessManager)
	if err != nil {
		return errors.NewField("AccessManager", err)
	}
	// Deserialize `Reserved`:
	err = decoder.Decode(&obj.Reserved)
	if err != nil {
		return errors.NewField("Reserved", err)
	}
	return nil
}

func (obj *AttestationLightClientTypesAppState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AttestationLightClientTypesAppState: %w", err)
	}
	return nil
}

func UnmarshalAttestationLightClientTypesAppState(buf []byte) (*AttestationLightClientTypesAppState, error) {
	obj := new(AttestationLightClientTypesAppState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Client state for the attestation light client
type AttestationLightClientTypesClientState struct {
	ClientId string `json:"clientId"`

	// Ethereum addresses of trusted attestors (20 bytes each)
	AttestorAddresses [][20]uint8 `json:"attestorAddresses"`
	MinRequiredSigs   uint8       `json:"minRequiredSigs"`
	LatestHeight      uint64      `json:"latestHeight"`
	IsFrozen          bool        `json:"isFrozen"`
}

func (obj AttestationLightClientTypesClientState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `ClientId`:
	err = encoder.Encode(obj.ClientId)
	if err != nil {
		return errors.NewField("ClientId", err)
	}
	// Serialize `AttestorAddresses`:
	err = encoder.Encode(obj.AttestorAddresses)
	if err != nil {
		return errors.NewField("AttestorAddresses", err)
	}
	// Serialize `MinRequiredSigs`:
	err = encoder.Encode(obj.MinRequiredSigs)
	if err != nil {
		return errors.NewField("MinRequiredSigs", err)
	}
	// Serialize `LatestHeight`:
	err = encoder.Encode(obj.LatestHeight)
	if err != nil {
		return errors.NewField("LatestHeight", err)
	}
	// Serialize `IsFrozen`:
	err = encoder.Encode(obj.IsFrozen)
	if err != nil {
		return errors.NewField("IsFrozen", err)
	}
	return nil
}

func (obj AttestationLightClientTypesClientState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AttestationLightClientTypesClientState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AttestationLightClientTypesClientState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `ClientId`:
	err = decoder.Decode(&obj.ClientId)
	if err != nil {
		return errors.NewField("ClientId", err)
	}
	// Deserialize `AttestorAddresses`:
	err = decoder.Decode(&obj.AttestorAddresses)
	if err != nil {
		return errors.NewField("AttestorAddresses", err)
	}
	// Deserialize `MinRequiredSigs`:
	err = decoder.Decode(&obj.MinRequiredSigs)
	if err != nil {
		return errors.NewField("MinRequiredSigs", err)
	}
	// Deserialize `LatestHeight`:
	err = decoder.Decode(&obj.LatestHeight)
	if err != nil {
		return errors.NewField("LatestHeight", err)
	}
	// Deserialize `IsFrozen`:
	err = decoder.Decode(&obj.IsFrozen)
	if err != nil {
		return errors.NewField("IsFrozen", err)
	}
	return nil
}

func (obj *AttestationLightClientTypesClientState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AttestationLightClientTypesClientState: %w", err)
	}
	return nil
}

func UnmarshalAttestationLightClientTypesClientState(buf []byte) (*AttestationLightClientTypesClientState, error) {
	obj := new(AttestationLightClientTypesClientState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Consensus state for the attestation light client
type AttestationLightClientTypesConsensusState struct {
	Height uint64 `json:"height"`

	// Timestamp in Unix seconds
	Timestamp uint64 `json:"timestamp"`
}

func (obj AttestationLightClientTypesConsensusState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Height`:
	err = encoder.Encode(obj.Height)
	if err != nil {
		return errors.NewField("Height", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj AttestationLightClientTypesConsensusState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AttestationLightClientTypesConsensusState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AttestationLightClientTypesConsensusState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Height`:
	err = decoder.Decode(&obj.Height)
	if err != nil {
		return errors.NewField("Height", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *AttestationLightClientTypesConsensusState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AttestationLightClientTypesConsensusState: %w", err)
	}
	return nil
}

func UnmarshalAttestationLightClientTypesConsensusState(buf []byte) (*AttestationLightClientTypesConsensusState, error) {
	obj := new(AttestationLightClientTypesConsensusState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Standard message structure for membership verification
// All light clients must accept this structure
type Ics25HandlerMembershipMsg struct {
	// The height at which to verify
	Height uint64 `json:"height"`

	// The merkle proof
	Proof []byte `json:"proof"`

	// The merkle path to the value
	Path [][]byte `json:"path"`

	// The value to verify
	Value []byte `json:"value"`
}

func (obj Ics25HandlerMembershipMsg) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Height`:
	err = encoder.Encode(obj.Height)
	if err != nil {
		return errors.NewField("Height", err)
	}
	// Serialize `Proof`:
	err = encoder.Encode(obj.Proof)
	if err != nil {
		return errors.NewField("Proof", err)
	}
	// Serialize `Path`:
	err = encoder.Encode(obj.Path)
	if err != nil {
		return errors.NewField("Path", err)
	}
	// Serialize `Value`:
	err = encoder.Encode(obj.Value)
	if err != nil {
		return errors.NewField("Value", err)
	}
	return nil
}

func (obj Ics25HandlerMembershipMsg) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Ics25HandlerMembershipMsg: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Ics25HandlerMembershipMsg) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Height`:
	err = decoder.Decode(&obj.Height)
	if err != nil {
		return errors.NewField("Height", err)
	}
	// Deserialize `Proof`:
	err = decoder.Decode(&obj.Proof)
	if err != nil {
		return errors.NewField("Proof", err)
	}
	// Deserialize `Path`:
	err = decoder.Decode(&obj.Path)
	if err != nil {
		return errors.NewField("Path", err)
	}
	// Deserialize `Value`:
	err = decoder.Decode(&obj.Value)
	if err != nil {
		return errors.NewField("Value", err)
	}
	return nil
}

func (obj *Ics25HandlerMembershipMsg) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Ics25HandlerMembershipMsg: %w", err)
	}
	return nil
}

func UnmarshalIcs25HandlerMembershipMsg(buf []byte) (*Ics25HandlerMembershipMsg, error) {
	obj := new(Ics25HandlerMembershipMsg)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Standard message structure for non-membership verification
// All light clients must accept this structure
type Ics25HandlerNonMembershipMsg struct {
	// The height at which to verify
	Height uint64 `json:"height"`

	// The merkle proof
	Proof []byte `json:"proof"`

	// The merkle path to the value
	Path [][]byte `json:"path"`
}

func (obj Ics25HandlerNonMembershipMsg) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Height`:
	err = encoder.Encode(obj.Height)
	if err != nil {
		return errors.NewField("Height", err)
	}
	// Serialize `Proof`:
	err = encoder.Encode(obj.Proof)
	if err != nil {
		return errors.NewField("Proof", err)
	}
	// Serialize `Path`:
	err = encoder.Encode(obj.Path)
	if err != nil {
		return errors.NewField("Path", err)
	}
	return nil
}

func (obj Ics25HandlerNonMembershipMsg) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Ics25HandlerNonMembershipMsg: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Ics25HandlerNonMembershipMsg) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Height`:
	err = decoder.Decode(&obj.Height)
	if err != nil {
		return errors.NewField("Height", err)
	}
	// Deserialize `Proof`:
	err = decoder.Decode(&obj.Proof)
	if err != nil {
		return errors.NewField("Proof", err)
	}
	// Deserialize `Path`:
	err = decoder.Decode(&obj.Path)
	if err != nil {
		return errors.NewField("Path", err)
	}
	return nil
}

func (obj *Ics25HandlerNonMembershipMsg) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Ics25HandlerNonMembershipMsg: %w", err)
	}
	return nil
}

func UnmarshalIcs25HandlerNonMembershipMsg(buf []byte) (*Ics25HandlerNonMembershipMsg, error) {
	obj := new(Ics25HandlerNonMembershipMsg)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
