[package]
name       = "cw-ibc-callbacks-helpers"
version    = { workspace = true }
edition    = { workspace = true }
repository = { workspace = true }
license    = { workspace = true }

[dependencies]
serde      = { workspace = true, features = ["derive"] }
prost      = { workspace = true, features = ["std"] }
serde_json = { workspace = true }

cosmwasm-std = { workspace = true, features = ["stargate"] }

ibc-proto = { workspace = true }
