// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package ift

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_Ics27GmpStateGmpCallResultAccount:
		value := new(Ics27GmpStateGmpCallResultAccount)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Ics27GmpStateGmpCallResultAccount: %w", err)
		}
		return value, nil
	case Account_IftStateIftAppMintState:
		value := new(IftStateIftAppMintState)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as IftStateIftAppMintState: %w", err)
		}
		return value, nil
	case Account_IftStateIftAppState:
		value := new(IftStateIftAppState)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as IftStateIftAppState: %w", err)
		}
		return value, nil
	case Account_IftStateIftBridge:
		value := new(IftStateIftBridge)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as IftStateIftBridge: %w", err)
		}
		return value, nil
	case Account_IftStatePendingTransfer:
		value := new(IftStatePendingTransfer)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as IftStatePendingTransfer: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_Ics27GmpStateGmpCallResultAccount(accountData []byte) (*Ics27GmpStateGmpCallResultAccount, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Ics27GmpStateGmpCallResultAccount {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Ics27GmpStateGmpCallResultAccount, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Ics27GmpStateGmpCallResultAccount)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Ics27GmpStateGmpCallResultAccount: %w", err)
	}
	return acc, nil
}

func ParseAccount_IftStateIftAppMintState(accountData []byte) (*IftStateIftAppMintState, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_IftStateIftAppMintState {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_IftStateIftAppMintState, binary.FormatDiscriminator(discriminator))
	}
	acc := new(IftStateIftAppMintState)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type IftStateIftAppMintState: %w", err)
	}
	return acc, nil
}

func ParseAccount_IftStateIftAppState(accountData []byte) (*IftStateIftAppState, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_IftStateIftAppState {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_IftStateIftAppState, binary.FormatDiscriminator(discriminator))
	}
	acc := new(IftStateIftAppState)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type IftStateIftAppState: %w", err)
	}
	return acc, nil
}

func ParseAccount_IftStateIftBridge(accountData []byte) (*IftStateIftBridge, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_IftStateIftBridge {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_IftStateIftBridge, binary.FormatDiscriminator(discriminator))
	}
	acc := new(IftStateIftBridge)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type IftStateIftBridge: %w", err)
	}
	return acc, nil
}

func ParseAccount_IftStatePendingTransfer(accountData []byte) (*IftStatePendingTransfer, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_IftStatePendingTransfer {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_IftStatePendingTransfer, binary.FormatDiscriminator(discriminator))
	}
	acc := new(IftStatePendingTransfer)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type IftStatePendingTransfer: %w", err)
	}
	return acc, nil
}
