// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: ibc_attestor/ibc_attestor.proto

package attestor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttestationService_StateAttestation_FullMethodName  = "/ibc_attestor.AttestationService/StateAttestation"
	AttestationService_PacketAttestation_FullMethodName = "/ibc_attestor.AttestationService/PacketAttestation"
	AttestationService_LatestHeight_FullMethodName      = "/ibc_attestor.AttestationService/LatestHeight"
)

// AttestationServiceClient is the client API for AttestationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for retrieving attestations.
type AttestationServiceClient interface {
	// Retrieves an attestation for a state at a given height.
	StateAttestation(ctx context.Context, in *StateAttestationRequest, opts ...grpc.CallOption) (*StateAttestationResponse, error)
	// Retrieves an attestation for a set of packets.
	PacketAttestation(ctx context.Context, in *PacketAttestationRequest, opts ...grpc.CallOption) (*PacketAttestationResponse, error)
	// Returns the latest height of the attested chain.
	LatestHeight(ctx context.Context, in *LatestHeightRequest, opts ...grpc.CallOption) (*LatestHeightResponse, error)
}

type attestationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttestationServiceClient(cc grpc.ClientConnInterface) AttestationServiceClient {
	return &attestationServiceClient{cc}
}

func (c *attestationServiceClient) StateAttestation(ctx context.Context, in *StateAttestationRequest, opts ...grpc.CallOption) (*StateAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateAttestationResponse)
	err := c.cc.Invoke(ctx, AttestationService_StateAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationServiceClient) PacketAttestation(ctx context.Context, in *PacketAttestationRequest, opts ...grpc.CallOption) (*PacketAttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PacketAttestationResponse)
	err := c.cc.Invoke(ctx, AttestationService_PacketAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationServiceClient) LatestHeight(ctx context.Context, in *LatestHeightRequest, opts ...grpc.CallOption) (*LatestHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatestHeightResponse)
	err := c.cc.Invoke(ctx, AttestationService_LatestHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttestationServiceServer is the server API for AttestationService service.
// All implementations must embed UnimplementedAttestationServiceServer
// for forward compatibility.
//
// Service definition for retrieving attestations.
type AttestationServiceServer interface {
	// Retrieves an attestation for a state at a given height.
	StateAttestation(context.Context, *StateAttestationRequest) (*StateAttestationResponse, error)
	// Retrieves an attestation for a set of packets.
	PacketAttestation(context.Context, *PacketAttestationRequest) (*PacketAttestationResponse, error)
	// Returns the latest height of the attested chain.
	LatestHeight(context.Context, *LatestHeightRequest) (*LatestHeightResponse, error)
	mustEmbedUnimplementedAttestationServiceServer()
}

// UnimplementedAttestationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttestationServiceServer struct{}

func (UnimplementedAttestationServiceServer) StateAttestation(context.Context, *StateAttestationRequest) (*StateAttestationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StateAttestation not implemented")
}
func (UnimplementedAttestationServiceServer) PacketAttestation(context.Context, *PacketAttestationRequest) (*PacketAttestationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PacketAttestation not implemented")
}
func (UnimplementedAttestationServiceServer) LatestHeight(context.Context, *LatestHeightRequest) (*LatestHeightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LatestHeight not implemented")
}
func (UnimplementedAttestationServiceServer) mustEmbedUnimplementedAttestationServiceServer() {}
func (UnimplementedAttestationServiceServer) testEmbeddedByValue()                            {}

// UnsafeAttestationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttestationServiceServer will
// result in compilation errors.
type UnsafeAttestationServiceServer interface {
	mustEmbedUnimplementedAttestationServiceServer()
}

func RegisterAttestationServiceServer(s grpc.ServiceRegistrar, srv AttestationServiceServer) {
	// If the following call panics, it indicates UnimplementedAttestationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttestationService_ServiceDesc, srv)
}

func _AttestationService_StateAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationServiceServer).StateAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationService_StateAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationServiceServer).StateAttestation(ctx, req.(*StateAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationService_PacketAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PacketAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationServiceServer).PacketAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationService_PacketAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationServiceServer).PacketAttestation(ctx, req.(*PacketAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationService_LatestHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatestHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationServiceServer).LatestHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationService_LatestHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationServiceServer).LatestHeight(ctx, req.(*LatestHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttestationService_ServiceDesc is the grpc.ServiceDesc for AttestationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttestationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ibc_attestor.AttestationService",
	HandlerType: (*AttestationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StateAttestation",
			Handler:    _AttestationService_StateAttestation_Handler,
		},
		{
			MethodName: "PacketAttestation",
			Handler:    _AttestationService_PacketAttestation_Handler,
		},
		{
			MethodName: "LatestHeight",
			Handler:    _AttestationService_LatestHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ibc_attestor/ibc_attestor.proto",
}
