pull_request_rules:
  - name: backport patches to v1.0.x branch
    conditions:
      - base=main
      - label=backport-to-v1.0.x
    actions:
      backport:
        branches:
          - release/v1.0.x
