//! Build script for copying events from ics26-router
//!
//! Events are defined in ics26-router (source of truth for Anchor IDL generation).
//! This script copies them to solana-ibc-types for use by relayers and other consumers.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    generate_events();
    println!("cargo:rerun-if-changed=build.rs");
}

fn generate_events() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let dest_path = Path::new(&manifest_dir).join("src/events.rs");

    let source_path = Path::new(&manifest_dir).join("../../programs/ics26-router/src/events.rs");

    println!("cargo:rerun-if-changed={}", source_path.display());

    let source_content =
        fs::read_to_string(&source_path).expect("Failed to read ics26-router/src/events.rs");

    let modified_content = source_content.replace(
        "use crate::state::{ClientAccount, Packet};",
        "use crate::router::{ClientAccount, Packet};",
    );

    let final_content = format!(
        "// AUTO-GENERATED FILE - DO NOT EDIT\n\
         // Generated by build.rs from ics26-router/src/events.rs\n\
         //\n\
         // WHY THIS EXISTS:\n\
         // Events are defined in ics26-router (source of truth for Anchor IDL generation).\n\
         // This copy allows relayers and other consumers to import events from solana-ibc-types.\n\
         //\n\
         // See build.rs for the generation logic.\n\n\
         {modified_content}"
    );

    fs::write(&dest_path, final_content).expect("Failed to write events.rs");
}
