[package]
name = "solana-types"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[features]
default = []
test-utils = []

[dependencies]
solana-sdk = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
borsh = { workspace = true }
schemars = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json = { workspace = true }
