[server]
  address = "0.0.0.0"
  port = 8080
  log_level = "debug"

[op]
  url = "https://eth-sepolia.g.alchemy.com/v2/iR-o8s0PPaLM7yCqrmna9ANzqvx7mF8B"
  router_address = "0xff42b3db9f1040539a3741434e4b33b352fabd80"
