FROM cosmwasm/optimizer:0.17.0 as rust-optimizer

RUN apk update && \
    apk add --no-cache clang llvm musl-dev libc-dev

WORKDIR /code

ENTRYPOINT ["optimize.sh"]
# Default argument when none is provided
CMD ["."]
