optimism_package:
  chains: # you can define multiple L2s, which will be deployed against the same L1 as a single Superchain
    chain0:
      participants:
        node0:
          el: # Executor
            type: op-geth
          cl: # Consensus
            type: op-node
            extra_env_vars:
              # Expose RPC endpoints documented here:
              # https://docs.optimism.io/operators/node-operators/json-rpc
              OP_NODE_CONDUCTOR_ENABLED: "true"
      network_params:
        network_id: 12345
