optimism_package:
  chains:
    chain0:
      participants:
        node0:
          el:
            type: op-geth
          cl:
            type: op-node
        node1:
          el:
            type: op-geth
          cl:
            type: op-node
ethereum_package:
  participants:
    - el_type: geth
      cl_type: lodestar
      cl_image: chainsafe/lodestar:v1.33.0
  network_params:
    preset: minimal
    genesis_delay: 5
    additional_preloaded_contracts: '
      {
        "0x4e59b44847b379578588920cA78FbF26c0B4956C": {
          "balance": "0ETH",
          "code": "0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf3",
          "storage": {},
          "nonce": "1"
        }
      }
    '