[package]
name = "ics24-host-solana"
version.workspace = true
edition.workspace = true
description = "ICS-24 host chain interface types and messages for IBC on Solana"
license.workspace = true
repository.workspace = true
readme = "../../../README.md"
keywords = ["cosmos", "ibc", "solana", "host", "ics24"]
categories = ["cryptography", "blockchain"]

[dependencies]
anchor-lang.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

