// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: aggregator/aggregator.proto

package aggregator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_aggregator_aggregator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_aggregator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_aggregator_aggregator_proto_rawDescGZIP(), []int{0}
}

func (x *Attestation) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Attestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinHeight     uint64                 `protobuf:"varint,1,opt,name=min_height,json=minHeight,proto3" json:"min_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_aggregator_aggregator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_aggregator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_aggregator_proto_rawDescGZIP(), []int{1}
}

func (x *QueryRequest) GetMinHeight() uint64 {
	if x != nil {
		return x.MinHeight
	}
	return 0
}

type AttestationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attestations  []*Attestation         `protobuf:"bytes,1,rep,name=attestations,proto3" json:"attestations,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"` // 65 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationsResponse) Reset() {
	*x = AttestationsResponse{}
	mi := &file_aggregator_aggregator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationsResponse) ProtoMessage() {}

func (x *AttestationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_aggregator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationsResponse.ProtoReflect.Descriptor instead.
func (*AttestationsResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_aggregator_proto_rawDescGZIP(), []int{2}
}

func (x *AttestationsResponse) GetAttestations() []*Attestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *AttestationsResponse) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type AggregateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinHeight     uint64                 `protobuf:"varint,1,opt,name=min_height,json=minHeight,proto3" json:"min_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateRequest) Reset() {
	*x = AggregateRequest{}
	mi := &file_aggregator_aggregator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRequest) ProtoMessage() {}

func (x *AggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_aggregator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRequest.ProtoReflect.Descriptor instead.
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_aggregator_proto_rawDescGZIP(), []int{3}
}

func (x *AggregateRequest) GetMinHeight() uint64 {
	if x != nil {
		return x.MinHeight
	}
	return 0
}

type AggregateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attestation   *Attestation           `protobuf:"bytes,1,opt,name=attestation,proto3,oneof" json:"attestation,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"` // 65 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateResponse) Reset() {
	*x = AggregateResponse{}
	mi := &file_aggregator_aggregator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateResponse) ProtoMessage() {}

func (x *AggregateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_aggregator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateResponse.ProtoReflect.Descriptor instead.
func (*AggregateResponse) Descriptor() ([]byte, []int) {
	return file_aggregator_aggregator_proto_rawDescGZIP(), []int{4}
}

func (x *AggregateResponse) GetAttestation() *Attestation {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *AggregateResponse) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

var File_aggregator_aggregator_proto protoreflect.FileDescriptor

const file_aggregator_aggregator_proto_rawDesc = "" +
	"\n" +
	"\x1baggregator/aggregator.proto\x12\n" +
	"aggregator\"C\n" +
	"\vAttestation\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"-\n" +
	"\fQueryRequest\x12\x1d\n" +
	"\n" +
	"min_height\x18\x01 \x01(\x04R\tminHeight\"k\n" +
	"\x14AttestationsResponse\x12;\n" +
	"\fattestations\x18\x01 \x03(\v2\x17.aggregator.AttestationR\fattestations\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\fR\x06pubkey\"1\n" +
	"\x10AggregateRequest\x12\x1d\n" +
	"\n" +
	"min_height\x18\x01 \x01(\x04R\tminHeight\"{\n" +
	"\x11AggregateResponse\x12>\n" +
	"\vattestation\x18\x01 \x01(\v2\x17.aggregator.AttestationH\x00R\vattestation\x88\x01\x01\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\fR\x06pubkeyB\x0e\n" +
	"\f_attestation2[\n" +
	"\bAttestor\x12O\n" +
	"\x11QueryAttestations\x12\x18.aggregator.QueryRequest\x1a .aggregator.AttestationsResponse2d\n" +
	"\n" +
	"Aggregator\x12V\n" +
	"\x17GetAggregateAttestation\x12\x1c.aggregator.AggregateRequest\x1a\x1d.aggregator.AggregateResponseB{\n" +
	"\x0ecom.aggregatorB\x0fAggregatorProtoP\x01Z\x10types/aggregator\xa2\x02\x03AXX\xaa\x02\n" +
	"Aggregator\xca\x02\n" +
	"Aggregator\xe2\x02\x16Aggregator\\GPBMetadata\xea\x02\n" +
	"Aggregatorb\x06proto3"

var (
	file_aggregator_aggregator_proto_rawDescOnce sync.Once
	file_aggregator_aggregator_proto_rawDescData []byte
)

func file_aggregator_aggregator_proto_rawDescGZIP() []byte {
	file_aggregator_aggregator_proto_rawDescOnce.Do(func() {
		file_aggregator_aggregator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aggregator_aggregator_proto_rawDesc), len(file_aggregator_aggregator_proto_rawDesc)))
	})
	return file_aggregator_aggregator_proto_rawDescData
}

var file_aggregator_aggregator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_aggregator_aggregator_proto_goTypes = []any{
	(*Attestation)(nil),          // 0: aggregator.Attestation
	(*QueryRequest)(nil),         // 1: aggregator.QueryRequest
	(*AttestationsResponse)(nil), // 2: aggregator.AttestationsResponse
	(*AggregateRequest)(nil),     // 3: aggregator.AggregateRequest
	(*AggregateResponse)(nil),    // 4: aggregator.AggregateResponse
}
var file_aggregator_aggregator_proto_depIdxs = []int32{
	0, // 0: aggregator.AttestationsResponse.attestations:type_name -> aggregator.Attestation
	0, // 1: aggregator.AggregateResponse.attestation:type_name -> aggregator.Attestation
	1, // 2: aggregator.Attestor.QueryAttestations:input_type -> aggregator.QueryRequest
	3, // 3: aggregator.Aggregator.GetAggregateAttestation:input_type -> aggregator.AggregateRequest
	2, // 4: aggregator.Attestor.QueryAttestations:output_type -> aggregator.AttestationsResponse
	4, // 5: aggregator.Aggregator.GetAggregateAttestation:output_type -> aggregator.AggregateResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aggregator_aggregator_proto_init() }
func file_aggregator_aggregator_proto_init() {
	if File_aggregator_aggregator_proto != nil {
		return
	}
	file_aggregator_aggregator_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aggregator_aggregator_proto_rawDesc), len(file_aggregator_aggregator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_aggregator_aggregator_proto_goTypes,
		DependencyIndexes: file_aggregator_aggregator_proto_depIdxs,
		MessageInfos:      file_aggregator_aggregator_proto_msgTypes,
	}.Build()
	File_aggregator_aggregator_proto = out.File
	file_aggregator_aggregator_proto_goTypes = nil
	file_aggregator_aggregator_proto_depIdxs = nil
}
