// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package access_manager

// Account discriminators
var (
	Account_AccessManagerStateAccessManager = [8]byte{129, 207, 58, 151, 47, 246, 92, 35}
)

// Event discriminators
var (
	Event_AccessManagerEventsProgramExtended = [8]byte{72, 55, 219, 203, 72, 77, 67, 116}
	Event_AccessManagerEventsProgramUpgraded = [8]byte{116, 102, 220, 4, 220, 250, 209, 13}
	Event_AccessManagerEventsRoleGranted     = [8]byte{220, 183, 89, 228, 143, 63, 246, 58}
	Event_AccessManagerEventsRoleRevoked     = [8]byte{167, 183, 52, 229, 126, 206, 62, 61}
)

// Instruction discriminators
var (
	Instruction_Initialize     = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_GrantRole      = [8]byte{218, 234, 128, 15, 82, 33, 236, 253}
	Instruction_RevokeRole     = [8]byte{179, 232, 2, 180, 48, 227, 82, 7}
	Instruction_RenounceRole   = [8]byte{21, 253, 233, 162, 186, 216, 217, 26}
	Instruction_UpgradeProgram = [8]byte{223, 236, 39, 89, 111, 204, 114, 37}
)
