// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package access_manager

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "initialize" instruction.
func NewInitializeInstruction(
	// Params:
	adminParam solanago.PublicKey,

	// Accounts:
	accessManagerAccount solanago.PublicKey,
	payerAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Initialize[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `adminParam`:
		err = enc__.Encode(adminParam)
		if err != nil {
			return nil, errors.NewField("adminParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "access_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(accessManagerAccount, true, false))
		// Account 1 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 2 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "grant_role" instruction.
func NewGrantRoleInstruction(
	// Params:
	roleIdParam uint64,
	accountParam solanago.PublicKey,

	// Accounts:
	accessManagerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_GrantRole[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `roleIdParam`:
		err = enc__.Encode(roleIdParam)
		if err != nil {
			return nil, errors.NewField("roleIdParam", err)
		}
		// Serialize `accountParam`:
		err = enc__.Encode(accountParam)
		if err != nil {
			return nil, errors.NewField("accountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "access_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(accessManagerAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "revoke_role" instruction.
func NewRevokeRoleInstruction(
	// Params:
	roleIdParam uint64,
	accountParam solanago.PublicKey,

	// Accounts:
	accessManagerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_RevokeRole[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `roleIdParam`:
		err = enc__.Encode(roleIdParam)
		if err != nil {
			return nil, errors.NewField("roleIdParam", err)
		}
		// Serialize `accountParam`:
		err = enc__.Encode(accountParam)
		if err != nil {
			return nil, errors.NewField("accountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "access_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(accessManagerAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "update_admin" instruction.
func NewUpdateAdminInstruction(
	// Params:
	newAdminParam solanago.PublicKey,

	// Accounts:
	accessManagerAccount solanago.PublicKey,
	currentAdminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_UpdateAdmin[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newAdminParam`:
		err = enc__.Encode(newAdminParam)
		if err != nil {
			return nil, errors.NewField("newAdminParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "access_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(accessManagerAccount, true, false))
		// Account 1 "current_admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(currentAdminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
