// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package access_manager

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type AccessManagerEventsProgramExtendedEvent struct {
	Program         solanago.PublicKey `json:"program"`
	Authority       solanago.PublicKey `json:"authority"`
	AdditionalBytes uint32             `json:"additionalBytes"`
	Timestamp       int64              `json:"timestamp"`
}

func (obj AccessManagerEventsProgramExtendedEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Program`:
	err = encoder.Encode(obj.Program)
	if err != nil {
		return errors.NewField("Program", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `AdditionalBytes`:
	err = encoder.Encode(obj.AdditionalBytes)
	if err != nil {
		return errors.NewField("AdditionalBytes", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj AccessManagerEventsProgramExtendedEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AccessManagerEventsProgramExtendedEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AccessManagerEventsProgramExtendedEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Program`:
	err = decoder.Decode(&obj.Program)
	if err != nil {
		return errors.NewField("Program", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `AdditionalBytes`:
	err = decoder.Decode(&obj.AdditionalBytes)
	if err != nil {
		return errors.NewField("AdditionalBytes", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *AccessManagerEventsProgramExtendedEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AccessManagerEventsProgramExtendedEvent: %w", err)
	}
	return nil
}

func UnmarshalAccessManagerEventsProgramExtendedEvent(buf []byte) (*AccessManagerEventsProgramExtendedEvent, error) {
	obj := new(AccessManagerEventsProgramExtendedEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type AccessManagerEventsProgramUpgradedEvent struct {
	Program   solanago.PublicKey `json:"program"`
	Authority solanago.PublicKey `json:"authority"`
	Timestamp int64              `json:"timestamp"`
}

func (obj AccessManagerEventsProgramUpgradedEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Program`:
	err = encoder.Encode(obj.Program)
	if err != nil {
		return errors.NewField("Program", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `Timestamp`:
	err = encoder.Encode(obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj AccessManagerEventsProgramUpgradedEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AccessManagerEventsProgramUpgradedEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AccessManagerEventsProgramUpgradedEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Program`:
	err = decoder.Decode(&obj.Program)
	if err != nil {
		return errors.NewField("Program", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `Timestamp`:
	err = decoder.Decode(&obj.Timestamp)
	if err != nil {
		return errors.NewField("Timestamp", err)
	}
	return nil
}

func (obj *AccessManagerEventsProgramUpgradedEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AccessManagerEventsProgramUpgradedEvent: %w", err)
	}
	return nil
}

func UnmarshalAccessManagerEventsProgramUpgradedEvent(buf []byte) (*AccessManagerEventsProgramUpgradedEvent, error) {
	obj := new(AccessManagerEventsProgramUpgradedEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type AccessManagerEventsRoleGrantedEvent struct {
	RoleId    uint64             `json:"roleId"`
	Account   solanago.PublicKey `json:"account"`
	GrantedBy solanago.PublicKey `json:"grantedBy"`
}

func (obj AccessManagerEventsRoleGrantedEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `RoleId`:
	err = encoder.Encode(obj.RoleId)
	if err != nil {
		return errors.NewField("RoleId", err)
	}
	// Serialize `Account`:
	err = encoder.Encode(obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Serialize `GrantedBy`:
	err = encoder.Encode(obj.GrantedBy)
	if err != nil {
		return errors.NewField("GrantedBy", err)
	}
	return nil
}

func (obj AccessManagerEventsRoleGrantedEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AccessManagerEventsRoleGrantedEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AccessManagerEventsRoleGrantedEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `RoleId`:
	err = decoder.Decode(&obj.RoleId)
	if err != nil {
		return errors.NewField("RoleId", err)
	}
	// Deserialize `Account`:
	err = decoder.Decode(&obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Deserialize `GrantedBy`:
	err = decoder.Decode(&obj.GrantedBy)
	if err != nil {
		return errors.NewField("GrantedBy", err)
	}
	return nil
}

func (obj *AccessManagerEventsRoleGrantedEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AccessManagerEventsRoleGrantedEvent: %w", err)
	}
	return nil
}

func UnmarshalAccessManagerEventsRoleGrantedEvent(buf []byte) (*AccessManagerEventsRoleGrantedEvent, error) {
	obj := new(AccessManagerEventsRoleGrantedEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type AccessManagerEventsRoleRevokedEvent struct {
	RoleId    uint64             `json:"roleId"`
	Account   solanago.PublicKey `json:"account"`
	RevokedBy solanago.PublicKey `json:"revokedBy"`
}

func (obj AccessManagerEventsRoleRevokedEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `RoleId`:
	err = encoder.Encode(obj.RoleId)
	if err != nil {
		return errors.NewField("RoleId", err)
	}
	// Serialize `Account`:
	err = encoder.Encode(obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Serialize `RevokedBy`:
	err = encoder.Encode(obj.RevokedBy)
	if err != nil {
		return errors.NewField("RevokedBy", err)
	}
	return nil
}

func (obj AccessManagerEventsRoleRevokedEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AccessManagerEventsRoleRevokedEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AccessManagerEventsRoleRevokedEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `RoleId`:
	err = decoder.Decode(&obj.RoleId)
	if err != nil {
		return errors.NewField("RoleId", err)
	}
	// Deserialize `Account`:
	err = decoder.Decode(&obj.Account)
	if err != nil {
		return errors.NewField("Account", err)
	}
	// Deserialize `RevokedBy`:
	err = decoder.Decode(&obj.RevokedBy)
	if err != nil {
		return errors.NewField("RevokedBy", err)
	}
	return nil
}

func (obj *AccessManagerEventsRoleRevokedEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AccessManagerEventsRoleRevokedEvent: %w", err)
	}
	return nil
}

func UnmarshalAccessManagerEventsRoleRevokedEvent(buf []byte) (*AccessManagerEventsRoleRevokedEvent, error) {
	obj := new(AccessManagerEventsRoleRevokedEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type AccessManagerEventsWhitelistedProgramsUpdatedEvent struct {
	OldPrograms []solanago.PublicKey `json:"oldPrograms"`
	NewPrograms []solanago.PublicKey `json:"newPrograms"`
	UpdatedBy   solanago.PublicKey   `json:"updatedBy"`
}

func (obj AccessManagerEventsWhitelistedProgramsUpdatedEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `OldPrograms`:
	err = encoder.Encode(obj.OldPrograms)
	if err != nil {
		return errors.NewField("OldPrograms", err)
	}
	// Serialize `NewPrograms`:
	err = encoder.Encode(obj.NewPrograms)
	if err != nil {
		return errors.NewField("NewPrograms", err)
	}
	// Serialize `UpdatedBy`:
	err = encoder.Encode(obj.UpdatedBy)
	if err != nil {
		return errors.NewField("UpdatedBy", err)
	}
	return nil
}

func (obj AccessManagerEventsWhitelistedProgramsUpdatedEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AccessManagerEventsWhitelistedProgramsUpdatedEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AccessManagerEventsWhitelistedProgramsUpdatedEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `OldPrograms`:
	err = decoder.Decode(&obj.OldPrograms)
	if err != nil {
		return errors.NewField("OldPrograms", err)
	}
	// Deserialize `NewPrograms`:
	err = decoder.Decode(&obj.NewPrograms)
	if err != nil {
		return errors.NewField("NewPrograms", err)
	}
	// Deserialize `UpdatedBy`:
	err = decoder.Decode(&obj.UpdatedBy)
	if err != nil {
		return errors.NewField("UpdatedBy", err)
	}
	return nil
}

func (obj *AccessManagerEventsWhitelistedProgramsUpdatedEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AccessManagerEventsWhitelistedProgramsUpdatedEvent: %w", err)
	}
	return nil
}

func UnmarshalAccessManagerEventsWhitelistedProgramsUpdatedEvent(buf []byte) (*AccessManagerEventsWhitelistedProgramsUpdatedEvent, error) {
	obj := new(AccessManagerEventsWhitelistedProgramsUpdatedEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Central role-based access control registry shared across all Solana IBC programs.
//
// Every program that requires permissioned operations (e.g. relaying, pausing,
// admin configuration) delegates authorization checks to this account.
// It stores a list of roles with their members and a whitelist of program IDs
// that are allowed to invoke admin-gated instructions via CPI.
type AccessManagerStateAccessManager struct {
	Roles               []AccessManagerTypesRoleData `json:"roles"`
	WhitelistedPrograms []solanago.PublicKey         `json:"whitelistedPrograms"`
}

func (obj AccessManagerStateAccessManager) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Roles`:
	err = encoder.Encode(obj.Roles)
	if err != nil {
		return errors.NewField("Roles", err)
	}
	// Serialize `WhitelistedPrograms`:
	err = encoder.Encode(obj.WhitelistedPrograms)
	if err != nil {
		return errors.NewField("WhitelistedPrograms", err)
	}
	return nil
}

func (obj AccessManagerStateAccessManager) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AccessManagerStateAccessManager: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AccessManagerStateAccessManager) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Roles`:
	err = decoder.Decode(&obj.Roles)
	if err != nil {
		return errors.NewField("Roles", err)
	}
	// Deserialize `WhitelistedPrograms`:
	err = decoder.Decode(&obj.WhitelistedPrograms)
	if err != nil {
		return errors.NewField("WhitelistedPrograms", err)
	}
	return nil
}

func (obj *AccessManagerStateAccessManager) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AccessManagerStateAccessManager: %w", err)
	}
	return nil
}

func UnmarshalAccessManagerStateAccessManager(buf []byte) (*AccessManagerStateAccessManager, error) {
	obj := new(AccessManagerStateAccessManager)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type AccessManagerTypesRoleData struct {
	RoleId  uint64               `json:"roleId"`
	Members []solanago.PublicKey `json:"members"`
}

func (obj AccessManagerTypesRoleData) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `RoleId`:
	err = encoder.Encode(obj.RoleId)
	if err != nil {
		return errors.NewField("RoleId", err)
	}
	// Serialize `Members`:
	err = encoder.Encode(obj.Members)
	if err != nil {
		return errors.NewField("Members", err)
	}
	return nil
}

func (obj AccessManagerTypesRoleData) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AccessManagerTypesRoleData: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AccessManagerTypesRoleData) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `RoleId`:
	err = decoder.Decode(&obj.RoleId)
	if err != nil {
		return errors.NewField("RoleId", err)
	}
	// Deserialize `Members`:
	err = decoder.Decode(&obj.Members)
	if err != nil {
		return errors.NewField("Members", err)
	}
	return nil
}

func (obj *AccessManagerTypesRoleData) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AccessManagerTypesRoleData: %w", err)
	}
	return nil
}

func UnmarshalAccessManagerTypesRoleData(buf []byte) (*AccessManagerTypesRoleData, error) {
	obj := new(AccessManagerTypesRoleData)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
