// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package access_manager

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Access manager account - wraps the shared type from solana-ibc-types
type AccessManagerStateAccessManager struct {
	V0 SolanaIbcTypesAccessManagerAccessManager `json:"v0"`
}

func (obj AccessManagerStateAccessManager) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `V0`:
	err = encoder.Encode(obj.V0)
	if err != nil {
		return errors.NewField("V0", err)
	}
	return nil
}

func (obj AccessManagerStateAccessManager) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding AccessManagerStateAccessManager: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *AccessManagerStateAccessManager) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `V0`:
	err = decoder.Decode(&obj.V0)
	if err != nil {
		return errors.NewField("V0", err)
	}
	return nil
}

func (obj *AccessManagerStateAccessManager) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling AccessManagerStateAccessManager: %w", err)
	}
	return nil
}

func UnmarshalAccessManagerStateAccessManager(buf []byte) (*AccessManagerStateAccessManager, error) {
	obj := new(AccessManagerStateAccessManager)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Access manager state - matches the on-chain account structure in access-manager program
type SolanaIbcTypesAccessManagerAccessManager struct {
	Roles []SolanaIbcTypesAccessManagerRoleData `json:"roles"`
}

func (obj SolanaIbcTypesAccessManagerAccessManager) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Roles`:
	err = encoder.Encode(obj.Roles)
	if err != nil {
		return errors.NewField("Roles", err)
	}
	return nil
}

func (obj SolanaIbcTypesAccessManagerAccessManager) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SolanaIbcTypesAccessManagerAccessManager: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SolanaIbcTypesAccessManagerAccessManager) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Roles`:
	err = decoder.Decode(&obj.Roles)
	if err != nil {
		return errors.NewField("Roles", err)
	}
	return nil
}

func (obj *SolanaIbcTypesAccessManagerAccessManager) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SolanaIbcTypesAccessManagerAccessManager: %w", err)
	}
	return nil
}

func UnmarshalSolanaIbcTypesAccessManagerAccessManager(buf []byte) (*SolanaIbcTypesAccessManagerAccessManager, error) {
	obj := new(SolanaIbcTypesAccessManagerAccessManager)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Role data containing role ID and members
type SolanaIbcTypesAccessManagerRoleData struct {
	RoleId  uint64               `json:"roleId"`
	Members []solanago.PublicKey `json:"members"`
}

func (obj SolanaIbcTypesAccessManagerRoleData) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `RoleId`:
	err = encoder.Encode(obj.RoleId)
	if err != nil {
		return errors.NewField("RoleId", err)
	}
	// Serialize `Members`:
	err = encoder.Encode(obj.Members)
	if err != nil {
		return errors.NewField("Members", err)
	}
	return nil
}

func (obj SolanaIbcTypesAccessManagerRoleData) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding SolanaIbcTypesAccessManagerRoleData: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *SolanaIbcTypesAccessManagerRoleData) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `RoleId`:
	err = decoder.Decode(&obj.RoleId)
	if err != nil {
		return errors.NewField("RoleId", err)
	}
	// Deserialize `Members`:
	err = decoder.Decode(&obj.Members)
	if err != nil {
		return errors.NewField("Members", err)
	}
	return nil
}

func (obj *SolanaIbcTypesAccessManagerRoleData) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling SolanaIbcTypesAccessManagerRoleData: %w", err)
	}
	return nil
}

func UnmarshalSolanaIbcTypesAccessManagerRoleData(buf []byte) (*SolanaIbcTypesAccessManagerRoleData, error) {
	obj := new(SolanaIbcTypesAccessManagerRoleData)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
