// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package test_ibc_app

// Account discriminators
var (
	Account_Ics26RouterStateClient         = [8]byte{221, 237, 145, 143, 170, 194, 133, 115}
	Account_Ics26RouterStateClientSequence = [8]byte{18, 97, 143, 135, 107, 101, 53, 226}
	Account_Ics26RouterStateIbcApp         = [8]byte{204, 125, 117, 159, 158, 163, 105, 66}
	Account_Ics26RouterStateRouterState    = [8]byte{141, 157, 194, 155, 75, 208, 200, 27}
	Account_TestIbcAppStateEscrowState     = [8]byte{19, 90, 148, 111, 55, 130, 229, 108}
	Account_TestIbcAppStateTestIbcAppState = [8]byte{134, 132, 47, 102, 214, 234, 207, 56}
)

// Event discriminators
var (
	Event_TestIbcAppInstructionsSendPacketPacketSent = [8]byte{88, 91, 33, 67, 248, 122, 173, 51}
	Event_TestIbcAppStatePacketAcknowledged          = [8]byte{199, 36, 235, 151, 125, 90, 168, 165}
	Event_TestIbcAppStatePacketReceived              = [8]byte{58, 84, 51, 248, 117, 120, 242, 178}
	Event_TestIbcAppStatePacketTimedOut              = [8]byte{45, 30, 55, 154, 41, 253, 155, 196}
	Event_TestIbcAppStateTransferSent                = [8]byte{1, 174, 197, 32, 9, 145, 255, 214}
)

// Instruction discriminators
var (
	Instruction_Initialize              = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_SendTransfer            = [8]byte{153, 182, 142, 63, 227, 31, 140, 239}
	Instruction_SendPacket              = [8]byte{242, 7, 23, 143, 124, 157, 42, 102}
	Instruction_OnRecvPacket            = [8]byte{153, 133, 78, 48, 156, 128, 229, 104}
	Instruction_OnAcknowledgementPacket = [8]byte{1, 142, 48, 169, 216, 66, 198, 31}
	Instruction_OnTimeoutPacket         = [8]byte{152, 10, 26, 185, 36, 193, 95, 76}
)
