// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package test_ibc_app

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_TestIbcAppInstructionsSendPacketPacketSent:
		value := new(TestIbcAppInstructionsSendPacketPacketSent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as TestIbcAppInstructionsSendPacketPacketSent: %w", err)
		}
		return value, nil
	case Event_TestIbcAppStatePacketAcknowledged:
		value := new(TestIbcAppStatePacketAcknowledged)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as TestIbcAppStatePacketAcknowledged: %w", err)
		}
		return value, nil
	case Event_TestIbcAppStatePacketReceived:
		value := new(TestIbcAppStatePacketReceived)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as TestIbcAppStatePacketReceived: %w", err)
		}
		return value, nil
	case Event_TestIbcAppStatePacketTimedOut:
		value := new(TestIbcAppStatePacketTimedOut)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as TestIbcAppStatePacketTimedOut: %w", err)
		}
		return value, nil
	case Event_TestIbcAppStateTransferSent:
		value := new(TestIbcAppStateTransferSent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as TestIbcAppStateTransferSent: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_TestIbcAppInstructionsSendPacketPacketSent(eventData []byte) (*TestIbcAppInstructionsSendPacketPacketSent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_TestIbcAppInstructionsSendPacketPacketSent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_TestIbcAppInstructionsSendPacketPacketSent, binary.FormatDiscriminator(discriminator))
	}
	event := new(TestIbcAppInstructionsSendPacketPacketSent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type TestIbcAppInstructionsSendPacketPacketSent: %w", err)
	}
	return event, nil
}

func ParseEvent_TestIbcAppStatePacketAcknowledged(eventData []byte) (*TestIbcAppStatePacketAcknowledged, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_TestIbcAppStatePacketAcknowledged {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_TestIbcAppStatePacketAcknowledged, binary.FormatDiscriminator(discriminator))
	}
	event := new(TestIbcAppStatePacketAcknowledged)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type TestIbcAppStatePacketAcknowledged: %w", err)
	}
	return event, nil
}

func ParseEvent_TestIbcAppStatePacketReceived(eventData []byte) (*TestIbcAppStatePacketReceived, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_TestIbcAppStatePacketReceived {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_TestIbcAppStatePacketReceived, binary.FormatDiscriminator(discriminator))
	}
	event := new(TestIbcAppStatePacketReceived)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type TestIbcAppStatePacketReceived: %w", err)
	}
	return event, nil
}

func ParseEvent_TestIbcAppStatePacketTimedOut(eventData []byte) (*TestIbcAppStatePacketTimedOut, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_TestIbcAppStatePacketTimedOut {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_TestIbcAppStatePacketTimedOut, binary.FormatDiscriminator(discriminator))
	}
	event := new(TestIbcAppStatePacketTimedOut)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type TestIbcAppStatePacketTimedOut: %w", err)
	}
	return event, nil
}

func ParseEvent_TestIbcAppStateTransferSent(eventData []byte) (*TestIbcAppStateTransferSent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_TestIbcAppStateTransferSent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_TestIbcAppStateTransferSent, binary.FormatDiscriminator(discriminator))
	}
	event := new(TestIbcAppStateTransferSent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type TestIbcAppStateTransferSent: %w", err)
	}
	return event, nil
}
