// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package test_ibc_app

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("8jmKPAswyWKqjHVpiNgGF9Yi4vbxeqvEhMbhmz5YvdwX")
