[package]
name = "ibc-eureka-relayer-lib"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[features]

[dependencies]
ibc-eureka-solidity-types = { workspace = true, features = ["rpc"] }

serde = { workspace = true, features = ["derive"] }
jsonrpsee = { workspace = true, features = ["client", "full", "tracing"] }
async-trait = { workspace = true }
anyhow = { workspace = true, features = ["std"] }

tendermint-rpc = { workspace = true, features = ["http-client"] }

alloy = { workspace = true, features = ["full", "node-bindings"] }
alloy-contract = { workspace = true }
