// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package gmp_counter_app

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("2ezUZ4tGV7CDKS7ypiGUA2FXRd2dNsqUAGZTaW8YDnmG")
