//! Build script for generating IBC constants
//!
//! This generates the `UNIVERSAL_ERROR_ACK` constant to ensure it matches
//! the Solidity implementation in contracts/utils/ICS24Host.sol

use sha2::{Digest as _, Sha256};
use std::env;
use std::fs;
use std::path::Path;

const SHA256_SIZE: usize = 32;

fn main() {
    // Compute UNIVERSAL_ERROR_ACK = sha256("UNIVERSAL_ERROR_ACKNOWLEDGEMENT")
    let universal_error_ack = compute_sha256(b"UNIVERSAL_ERROR_ACKNOWLEDGEMENT");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR environment variable not set");
    let dest_path = Path::new(&out_dir).join("constants.rs");

    let content = format!(
        r#"// Auto-generated by build.rs - DO NOT EDIT
// IBC constants that must match cross-chain implementations

/// Universal error acknowledgement as defined in ICS-04
/// This is `sha256("UNIVERSAL_ERROR_ACKNOWLEDGEMENT")`
/// Must match Solidity's `ICS24Host.UNIVERSAL_ERROR_ACK` for cross-chain compatibility
pub const UNIVERSAL_ERROR_ACK: &[u8] = &{universal_error_ack:?};
"#
    );

    fs::write(&dest_path, content).expect("Failed to write constants.rs");

    println!("cargo:rerun-if-changed=build.rs");
}

fn compute_sha256(data: &[u8]) -> [u8; SHA256_SIZE] {
    let mut hasher = Sha256::new();
    hasher.update(data);
    let hash_result = hasher.finalize();

    let mut hash = [0u8; SHA256_SIZE];
    hash.copy_from_slice(&hash_result);
    hash
}
