//! Build script for copying events
//!
//! This generates `events.rs` copied from `solana_ibc_types` for Anchor IDL generation.
//!
//! WHY EVENTS ARE COPIED:
//! Anchor's IDL generation only includes events defined with #[event] in the
//! same crate. Events in `solana_ibc_types` are used at runtime, but anchor-go
//! needs them in the IDL to generate Go types for event parsing.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    generate_events();

    println!("cargo:rerun-if-changed=build.rs");
}

fn generate_events() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let dest_path = Path::new(&manifest_dir).join("src/events.rs");

    // Path to solana_ibc_types events.rs (relative to ics26-router)
    let source_path =
        Path::new(&manifest_dir).join("../../packages/solana-ibc-types/src/events.rs");

    println!("cargo:rerun-if-changed={}", source_path.display());

    let source_content =
        fs::read_to_string(&source_path).expect("Failed to read solana_ibc_types/src/events.rs");

    // Replace the import to use local state re-exports
    let modified_content = source_content.replace(
        "use crate::router::{ClientAccount, Packet};",
        "use crate::state::{ClientAccount, Packet};",
    );

    // Add header explaining this is auto-generated
    let final_content = format!(
        "// AUTO-GENERATED FILE - DO NOT EDIT\n\
         // Generated by build.rs from solana_ibc_types/src/events.rs\n\
         //\n\
         // WHY THIS EXISTS:\n\
         // Anchor's IDL generation only includes events with #[event] defined in the\n\
         // same crate. The actual event emission uses solana_ibc_types versions, but\n\
         // anchor-go needs these definitions in the IDL to generate Go event parsers.\n\
         //\n\
         // See build.rs for the generation logic.\n\n\
         {modified_content}"
    );

    fs::write(&dest_path, final_content).expect("Failed to write events.rs");
}
