version: '3'
services:
  loki:
    image: grafana/loki:${GRAFANA_LOKI_VERSION:-3.5.2}
    ports:
      - "3100:3100"
    volumes:
     - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
  tempo:
    image: grafana/tempo:${GRAFANA_TEMPO_VERSION:-2.7.1}
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"   # Tempo HTTP UI / API
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v3.5.0}
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
   image: grafana/grafana:${GRAFANA_VERSION:-12.0.2}
   environment:
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_BASIC_ENABLED=false
   ports:
     - 3002:3000/tcp
   entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Tempo
          type: tempo
          access: proxy
          orgId: 1
          url: http://tempo:3200
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh

  alloy:
   image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.10.0}
   privileged: true
   ports:
     - 12345:12345
     - 4317:4317
     - 4318:4318
   environment:
      ALLOY_DEPLOY_MODE: docker
   volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /proc:/rootproc:ro
      - /var/run/docker.sock.raw:/var/run/docker.sock
      - /sys:/sys:ro
      - /:/rootfs:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
   command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
   extra_hosts:
        - "host.docker.internal:host-gateway"
   devices:
        - /dev/kmsg