[package]
name = "ethereum-apis"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
ethereum-types = { workspace = true }

alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-transport = { workspace = true }
alloy-rpc-types-eth = { workspace = true, features = ["serde"] }

reqwest = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
