/// Defines the API for the server generated by tonic.
#[allow(clippy::nursery, clippy::pedantic)]
pub mod api {
    tonic::include_proto!("ibc_attestor");
    pub(crate) const FILE_DESCRIPTOR_SET: &[u8] =
        tonic::include_file_descriptor_set!("ibc_attestor_descriptor");
}

pub mod adapter_client;
pub mod attestor;
pub mod cli;
pub mod server;
pub mod signer;

mod adapter_impls;
mod error;

#[cfg(feature = "arbitrum")]
pub use adapter_impls::arbitrum::*;

#[cfg(feature = "op")]
pub use adapter_impls::optimism::*;

#[cfg(feature = "sol")]
pub use adapter_impls::sol::*;

#[cfg(feature = "cosmos")]
pub use adapter_impls::cosmos::*;

pub use error::AttestorError;
