[package]
name = "ethereum-types"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
ethereum-utils = { workspace = true }
alloy-primitives = { workspace = true, features = ["serde", "hex-compat"] }
serde = { workspace = true, features = ["derive"] }
schemars = { workspace = true }
tree_hash = { workspace = true }
tree_hash_derive = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

