[package]
name = "sig-aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.13"
prost = "0.14"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"
thiserror = "2.0"
rand = "0.9"
clap = { version = "4.4", features = ["derive"] }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
hex = "0.4"

[build-dependencies]
tonic-build = "0.13"
