[server]
listner_addr = "127.0.0.1:50060"

[attestor]
attestor_query_timeout_ms = 5000
quorum_threshold = 1
attestor_endpoints = [
    "http://127.0.0.1:8080",
    # "second attestor endpoint",
    # "third attestor endpoint",
    # "and so on"
]
