[server]
listener_addr = "127.0.0.1:8080"
log_level = "INFO"

[attestor]
attestor_query_timeout_ms = 5000
quorum_threshold = 1
attestor_endpoints = [
    "http://127.0.0.1:9000",
    # "second attestor endpoint",
    # "third attestor endpoint",
    # "and so on"
]

[cache]
state_cache_max_entries = 100000
packet_cache_max_entries = 100000
