name: e2e-setup

inputs:
  github_token:
    description: A Github PAT
    required: true

runs:
  using: composite
  steps:
    - name: Set up foundry tooling
      uses: ./.github/actions/foundry-setup

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.25
        check-latest: true
        cache-dependency-path: e2e/interchaintestv8/go.sum

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: e2e-build-artifacts
        path: e2e-artifacts/

    - name: Cache Solana
      id: cache-solana
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
          ~/.cargo/bin/anchor
          ./programs/solana/target/deploy/
          ./programs/solana/target/sbpf-solana-solana/
        key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}-${{ env.ANCHOR_VERSION }}-${{ hashFiles('programs/solana/**') }}

    - name: Install artifacts
      shell: bash
      run: |
        # Install binaries
        chmod +x e2e-artifacts/bin/*
        mkdir -p ~/.cargo/bin
        cp e2e-artifacts/bin/* ~/.cargo/bin/
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

        # Install SP1 programs
        mkdir -p programs/sp1-programs/target/elf-compilation/riscv32im-succinct-zkvm-elf/release/
        cp -r e2e-artifacts/sp1-programs/* programs/sp1-programs/target/elf-compilation/riscv32im-succinct-zkvm-elf/release/

    - name: Setup Kurtosis
      if: env.ETH_TESTNET_TYPE == 'pos'
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install kurtosis-cli=1.11.2 # Must match the kurtosis library version we use in the e2e tests
        kurtosis engine start
        kurtosis analytics disable
        echo "$(dirname $(which kurtosis))" >> $GITHUB_PATH

    - name: Setup Solana Dependencies
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libudev-dev llvm libclang-dev protobuf-compiler libssl-dev

    - name: Setup Solana
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v${SOLANA_VERSION}/install)"

    - name: Add Solana to PATH
      shell: bash
      run: |
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Setup Anchor
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
      run: cargo install --git https://github.com/coral-xyz/anchor --tag v${ANCHOR_VERSION} anchor-cli

    - name: Install just
      uses: extractions/setup-just@v2

    - name: Build Solana Programs
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
      run: just build-solana
