name: e2e-setup

inputs:
  github_token:
    description: A Github PAT
    required: true

runs:
  using: composite
  steps:
    - name: Set up foundry tooling
      uses: ./.github/actions/foundry-setup

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
        check-latest: true
        cache-dependency-path: e2e/interchaintestv8/go.sum

    - name: Cache Relayer and Operator
      id: cache-relayer
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/relayer
          ~/.cargo/bin/operator
          ./programs/sp1-programs/target/elf-compilation/riscv32im-succinct-zkvm-elf/release/*
        key: ${{ runner.os }}-relayer-${{ hashFiles('Cargo.lock', 'Cargo.toml', 'packages/**', 'programs/**', 'abi/**') }}

    - name: Cache Solana
      id: cache-solana
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
          ~/.cargo/bin/anchor
          ./programs/solana/target/deploy/
          ./programs/solana/target/sbpf-solana-solana/
        key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}-${{ env.ANCHOR_VERSION }}-${{ hashFiles('programs/solana/**') }}

    - name: Install SP1 toolchain
      if: (steps.cache-relayer.outputs.cache-hit != 'true')
      shell: bash
      run: |
        curl -L https://sp1.succinct.xyz | bash
        ~/.sp1/bin/sp1up --token ${{ inputs.github_token }}
        ~/.sp1/bin/cargo-prove prove --version

    - name: Install operator
      if: steps.cache-relayer.outputs.cache-hit != 'true'
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --bin operator --path programs/operator --locked

    - name: Install relayer
      if: steps.cache-relayer.outputs.cache-hit != 'true'
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --bin relayer --path programs/relayer --locked

    - name: Install just
      uses: extractions/setup-just@v2

    - name: Build SP1 Programs
      if: (steps.cache-relayer.outputs.cache-hit != 'true')
      shell: bash
      run: just build-sp1-programs

    - name: Setup Kurtosis
      if: env.ETH_TESTNET_TYPE == 'pos'
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install kurtosis-cli=1.10.3 # Must match the kurtosis library version we use in the e2e tests
        kurtosis engine start
        kurtosis analytics disable
        echo "$(dirname $(which kurtosis))" >> $GITHUB_PATH

    - name: Setup Solana Dependencies
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libudev-dev llvm libclang-dev protobuf-compiler libssl-dev

    - name: Setup Solana
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v${SOLANA_VERSION}/install)"

    - name: Add Solana to PATH
      shell: bash
      run: |
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Setup Anchor
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
      run: cargo install --git https://github.com/coral-xyz/anchor --tag v${ANCHOR_VERSION} anchor-cli

    - name: Build Solana Programs
      if: steps.cache-solana.outputs.cache-hit != 'true'
      shell: bash
      run: just build-solana
