// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package ics26_router

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("CAvhnCbHDv43XxgtvRqcee54yJakHePgfCic1yYdNQFC")
