// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package ics26_router

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("J7fPyt4Lb2RkNXNU5CpRQEbfvgNak5U2UnEr9fAb9ezY")
