// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package ics07_tendermint

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "initialize" instruction.
func NewInitializeInstruction(
	// Params:
	latestHeightParam uint64,
	clientStateParam ClientState,
	consensusStateParam ConsensusState,

	// Accounts:
	clientStateAccount solanago.PublicKey,
	consensusStateStoreAccount solanago.PublicKey,
	payerAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Initialize[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `latestHeightParam`:
		err = enc__.Encode(latestHeightParam)
		if err != nil {
			return nil, errors.NewField("latestHeightParam", err)
		}
		// Serialize `clientStateParam`:
		err = enc__.Encode(clientStateParam)
		if err != nil {
			return nil, errors.NewField("clientStateParam", err)
		}
		// Serialize `consensusStateParam`:
		err = enc__.Encode(consensusStateParam)
		if err != nil {
			return nil, errors.NewField("consensusStateParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "client_state": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clientStateAccount, true, false))
		// Account 1 "consensus_state_store": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(consensusStateStoreAccount, true, false))
		// Account 2 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 3 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "submit_misbehaviour" instruction.
func NewSubmitMisbehaviourInstruction(
	// Params:
	msgParam MisbehaviourMsg,

	// Accounts:
	clientStateAccount solanago.PublicKey,
	trustedConsensusState1account solanago.PublicKey,
	trustedConsensusState2account solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SubmitMisbehaviour[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `msgParam`:
		err = enc__.Encode(msgParam)
		if err != nil {
			return nil, errors.NewField("msgParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "client_state": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clientStateAccount, true, false))
		// Account 1 "trusted_consensus_state_1": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(trustedConsensusState1account, false, false))
		// Account 2 "trusted_consensus_state_2": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(trustedConsensusState2account, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "update_client" instruction.
func NewUpdateClientInstruction(
	// Params:
	msgParam UpdateClientMsg,

	// Accounts:
	clientStateAccount solanago.PublicKey,
	trustedConsensusStateAccount solanago.PublicKey,
	newConsensusStateStoreAccount solanago.PublicKey,
	payerAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_UpdateClient[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `msgParam`:
		err = enc__.Encode(msgParam)
		if err != nil {
			return nil, errors.NewField("msgParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "client_state": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clientStateAccount, true, false))
		// Account 1 "trusted_consensus_state": Read-only, Non-signer, Required
		// Trusted consensus state at the height specified in the header
		accounts__.Append(solanago.NewAccountMeta(trustedConsensusStateAccount, false, false))
		// Account 2 "new_consensus_state_store": Read-only, Non-signer, Required
		// Consensus state store for the new height - will be created or validated
		accounts__.Append(solanago.NewAccountMeta(newConsensusStateStoreAccount, false, false))
		// Account 3 "payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 4 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "verify_membership" instruction.
func NewVerifyMembershipInstruction(
	// Params:
	msgParam MembershipMsg,

	// Accounts:
	clientStateAccount solanago.PublicKey,
	consensusStateAtHeightAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_VerifyMembership[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `msgParam`:
		err = enc__.Encode(msgParam)
		if err != nil {
			return nil, errors.NewField("msgParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "client_state": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clientStateAccount, false, false))
		// Account 1 "consensus_state_at_height": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(consensusStateAtHeightAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "verify_non_membership" instruction.
func NewVerifyNonMembershipInstruction(
	// Params:
	msgParam MembershipMsg,

	// Accounts:
	clientStateAccount solanago.PublicKey,
	consensusStateAtHeightAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_VerifyNonMembership[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `msgParam`:
		err = enc__.Encode(msgParam)
		if err != nil {
			return nil, errors.NewField("msgParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "client_state": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clientStateAccount, false, false))
		// Account 1 "consensus_state_at_height": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(consensusStateAtHeightAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
