// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package ics07_tendermint

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("8wQAC7oWLTxExhR49jYAzXZB39mu7WVVvkWJGgAMMjpV")
