[package]
name = "attestor-packet-membership"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[features]
default = []

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
schemars = { workspace = true }

[dev-dependencies]
ibc = { workspace = true, features = ["serde"] }
