[package]
name = "attestor-packet-membership"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[features]
default = []

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
