[package]
name = "packet-membership"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[features]
default = []

[dependencies]
borsh = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
schemars = { workspace = true }

[dev-dependencies]
ibc = { workspace = true, features = ["borsh"] }
