// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package mock_light_client

// Account discriminators
var ()

// Event discriminators
var ()

// Instruction discriminators
var (
	Instruction_Initialize          = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_VerifyMembership    = [8]byte{101, 53, 78, 0, 103, 151, 236, 209}
	Instruction_VerifyNonMembership = [8]byte{231, 161, 86, 239, 111, 236, 14, 74}
	Instruction_UpdateClient        = [8]byte{184, 89, 17, 76, 97, 57, 165, 10}
)
