// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package mock_light_client

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("J3CqL1NXm8a7oAxDt3QPpmqNboXheUSs733y9SzRGT5B")
