[package]
name       = "ibc-eureka-relayer-eth-to-cosmos-attested"
version    = { workspace = true }
edition    = { workspace = true }
repository = { workspace = true }
license    = { workspace = true }

[dependencies]
ibc-eureka-relayer-lib    = { workspace = true, default-features = false }
ibc-eureka-relayer-core   = { workspace = true, default-features = false }
ibc-eureka-utils          = { workspace = true }
alloy = { workspace = true, features = ["full", "node-bindings"] }
alloy-primitives = { workspace = true, default-features = false, features = ["k256"] }

serde      = { workspace = true, features = ["derive"] }
prost      = { workspace = true, features = ["std"] }
serde_json = { workspace = true }

tonic         = { workspace = true, default-features = true }
async-trait   = { workspace = true }
anyhow        = { workspace = true, features = ["std"] }
tracing       = { workspace = true, default-features = true }

tendermint     = { workspace = true }
tendermint-rpc = { workspace = true, features = ["http-client"] }
hex            = { workspace = true }

attestor-light-client = { workspace = true }

ibc-proto-eureka          = { workspace = true }
ibc-eureka-solidity-types = { workspace = true, default-features = true }

[build-dependencies]
tonic-build = { workspace = true }

[dev-dependencies]
attestor-packet-membership = { workspace = true }