// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: tokenfactory/tx.proto

package tokenfactory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgCreateDenom creates a new token denomination
type MsgCreateDenom struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sender is the address creating the denom
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// subdenom is the subdenom identifier
	Subdenom      string `protobuf:"bytes,2,opt,name=subdenom,proto3" json:"subdenom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateDenom) Reset() {
	*x = MsgCreateDenom{}
	mi := &file_tokenfactory_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateDenom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateDenom) ProtoMessage() {}

func (x *MsgCreateDenom) ProtoReflect() protoreflect.Message {
	mi := &file_tokenfactory_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateDenom.ProtoReflect.Descriptor instead.
func (*MsgCreateDenom) Descriptor() ([]byte, []int) {
	return file_tokenfactory_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreateDenom) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgCreateDenom) GetSubdenom() string {
	if x != nil {
		return x.Subdenom
	}
	return ""
}

// MsgCreateDenomResponse is the response for MsgCreateDenom
type MsgCreateDenomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// new_token_denom is the full denom string created
	NewTokenDenom string `protobuf:"bytes,1,opt,name=new_token_denom,json=newTokenDenom,proto3" json:"new_token_denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateDenomResponse) Reset() {
	*x = MsgCreateDenomResponse{}
	mi := &file_tokenfactory_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateDenomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateDenomResponse) ProtoMessage() {}

func (x *MsgCreateDenomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tokenfactory_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateDenomResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateDenomResponse) Descriptor() ([]byte, []int) {
	return file_tokenfactory_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCreateDenomResponse) GetNewTokenDenom() string {
	if x != nil {
		return x.NewTokenDenom
	}
	return ""
}

// MsgMint mints tokens of a factory denom
type MsgMint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sender is the address minting tokens (must be denom admin)
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// amount is the coin to mint (denom + amount)
	Amount *Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// mint_to_address is the recipient of the minted tokens
	MintToAddress string `protobuf:"bytes,3,opt,name=mint_to_address,json=mintToAddress,proto3" json:"mint_to_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMint) Reset() {
	*x = MsgMint{}
	mi := &file_tokenfactory_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMint) ProtoMessage() {}

func (x *MsgMint) ProtoReflect() protoreflect.Message {
	mi := &file_tokenfactory_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMint.ProtoReflect.Descriptor instead.
func (*MsgMint) Descriptor() ([]byte, []int) {
	return file_tokenfactory_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgMint) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgMint) GetAmount() *Coin {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *MsgMint) GetMintToAddress() string {
	if x != nil {
		return x.MintToAddress
	}
	return ""
}

// MsgMintResponse is the response for MsgMint
type MsgMintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMintResponse) Reset() {
	*x = MsgMintResponse{}
	mi := &file_tokenfactory_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMintResponse) ProtoMessage() {}

func (x *MsgMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tokenfactory_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMintResponse.ProtoReflect.Descriptor instead.
func (*MsgMintResponse) Descriptor() ([]byte, []int) {
	return file_tokenfactory_tx_proto_rawDescGZIP(), []int{3}
}

// MsgBurn burns tokens of a factory denom
type MsgBurn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sender is the address burning tokens (must be denom admin)
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// amount is the coin to burn
	Amount *Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// burn_from_address is the address to burn from
	BurnFromAddress string `protobuf:"bytes,3,opt,name=burn_from_address,json=burnFromAddress,proto3" json:"burn_from_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MsgBurn) Reset() {
	*x = MsgBurn{}
	mi := &file_tokenfactory_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBurn) ProtoMessage() {}

func (x *MsgBurn) ProtoReflect() protoreflect.Message {
	mi := &file_tokenfactory_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBurn.ProtoReflect.Descriptor instead.
func (*MsgBurn) Descriptor() ([]byte, []int) {
	return file_tokenfactory_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgBurn) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgBurn) GetAmount() *Coin {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *MsgBurn) GetBurnFromAddress() string {
	if x != nil {
		return x.BurnFromAddress
	}
	return ""
}

// MsgBurnResponse is the response for MsgBurn
type MsgBurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBurnResponse) Reset() {
	*x = MsgBurnResponse{}
	mi := &file_tokenfactory_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBurnResponse) ProtoMessage() {}

func (x *MsgBurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tokenfactory_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBurnResponse.ProtoReflect.Descriptor instead.
func (*MsgBurnResponse) Descriptor() ([]byte, []int) {
	return file_tokenfactory_tx_proto_rawDescGZIP(), []int{5}
}

// MsgChangeAdmin changes the admin of a factory denom
type MsgChangeAdmin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sender is the current admin
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// denom is the factory denom
	Denom string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	// new_admin is the new admin address
	NewAdmin      string `protobuf:"bytes,3,opt,name=new_admin,json=newAdmin,proto3" json:"new_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgChangeAdmin) Reset() {
	*x = MsgChangeAdmin{}
	mi := &file_tokenfactory_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgChangeAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgChangeAdmin) ProtoMessage() {}

func (x *MsgChangeAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_tokenfactory_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgChangeAdmin.ProtoReflect.Descriptor instead.
func (*MsgChangeAdmin) Descriptor() ([]byte, []int) {
	return file_tokenfactory_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgChangeAdmin) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgChangeAdmin) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *MsgChangeAdmin) GetNewAdmin() string {
	if x != nil {
		return x.NewAdmin
	}
	return ""
}

// MsgChangeAdminResponse is the response for MsgChangeAdmin
type MsgChangeAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgChangeAdminResponse) Reset() {
	*x = MsgChangeAdminResponse{}
	mi := &file_tokenfactory_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgChangeAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgChangeAdminResponse) ProtoMessage() {}

func (x *MsgChangeAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tokenfactory_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgChangeAdminResponse.ProtoReflect.Descriptor instead.
func (*MsgChangeAdminResponse) Descriptor() ([]byte, []int) {
	return file_tokenfactory_tx_proto_rawDescGZIP(), []int{7}
}

// Coin represents a token with amount and denomination
type Coin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coin) Reset() {
	*x = Coin{}
	mi := &file_tokenfactory_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coin) ProtoMessage() {}

func (x *Coin) ProtoReflect() protoreflect.Message {
	mi := &file_tokenfactory_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coin.ProtoReflect.Descriptor instead.
func (*Coin) Descriptor() ([]byte, []int) {
	return file_tokenfactory_tx_proto_rawDescGZIP(), []int{8}
}

func (x *Coin) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Coin) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_tokenfactory_tx_proto protoreflect.FileDescriptor

const file_tokenfactory_tx_proto_rawDesc = "" +
	"\n" +
	"\x15tokenfactory/tx.proto\x12\ftokenfactory\"D\n" +
	"\x0eMsgCreateDenom\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\bsubdenom\x18\x02 \x01(\tR\bsubdenom\"@\n" +
	"\x16MsgCreateDenomResponse\x12&\n" +
	"\x0fnew_token_denom\x18\x01 \x01(\tR\rnewTokenDenom\"u\n" +
	"\aMsgMint\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12*\n" +
	"\x06amount\x18\x02 \x01(\v2\x12.tokenfactory.CoinR\x06amount\x12&\n" +
	"\x0fmint_to_address\x18\x03 \x01(\tR\rmintToAddress\"\x11\n" +
	"\x0fMsgMintResponse\"y\n" +
	"\aMsgBurn\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12*\n" +
	"\x06amount\x18\x02 \x01(\v2\x12.tokenfactory.CoinR\x06amount\x12*\n" +
	"\x11burn_from_address\x18\x03 \x01(\tR\x0fburnFromAddress\"\x11\n" +
	"\x0fMsgBurnResponse\"[\n" +
	"\x0eMsgChangeAdmin\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x14\n" +
	"\x05denom\x18\x02 \x01(\tR\x05denom\x12\x1b\n" +
	"\tnew_admin\x18\x03 \x01(\tR\bnewAdmin\"\x18\n" +
	"\x16MsgChangeAdminResponse\"4\n" +
	"\x04Coin\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amountB\x7f\n" +
	"\x10com.tokenfactoryB\aTxProtoP\x01Z\x12types/tokenfactory\xa2\x02\x03TXX\xaa\x02\fTokenfactory\xca\x02\fTokenfactory\xe2\x02\x18Tokenfactory\\GPBMetadata\xea\x02\fTokenfactoryb\x06proto3"

var (
	file_tokenfactory_tx_proto_rawDescOnce sync.Once
	file_tokenfactory_tx_proto_rawDescData []byte
)

func file_tokenfactory_tx_proto_rawDescGZIP() []byte {
	file_tokenfactory_tx_proto_rawDescOnce.Do(func() {
		file_tokenfactory_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tokenfactory_tx_proto_rawDesc), len(file_tokenfactory_tx_proto_rawDesc)))
	})
	return file_tokenfactory_tx_proto_rawDescData
}

var file_tokenfactory_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tokenfactory_tx_proto_goTypes = []any{
	(*MsgCreateDenom)(nil),         // 0: tokenfactory.MsgCreateDenom
	(*MsgCreateDenomResponse)(nil), // 1: tokenfactory.MsgCreateDenomResponse
	(*MsgMint)(nil),                // 2: tokenfactory.MsgMint
	(*MsgMintResponse)(nil),        // 3: tokenfactory.MsgMintResponse
	(*MsgBurn)(nil),                // 4: tokenfactory.MsgBurn
	(*MsgBurnResponse)(nil),        // 5: tokenfactory.MsgBurnResponse
	(*MsgChangeAdmin)(nil),         // 6: tokenfactory.MsgChangeAdmin
	(*MsgChangeAdminResponse)(nil), // 7: tokenfactory.MsgChangeAdminResponse
	(*Coin)(nil),                   // 8: tokenfactory.Coin
}
var file_tokenfactory_tx_proto_depIdxs = []int32{
	8, // 0: tokenfactory.MsgMint.amount:type_name -> tokenfactory.Coin
	8, // 1: tokenfactory.MsgBurn.amount:type_name -> tokenfactory.Coin
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tokenfactory_tx_proto_init() }
func file_tokenfactory_tx_proto_init() {
	if File_tokenfactory_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tokenfactory_tx_proto_rawDesc), len(file_tokenfactory_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tokenfactory_tx_proto_goTypes,
		DependencyIndexes: file_tokenfactory_tx_proto_depIdxs,
		MessageInfos:      file_tokenfactory_tx_proto_msgTypes,
	}.Build()
	File_tokenfactory_tx_proto = out.File
	file_tokenfactory_tx_proto_goTypes = nil
	file_tokenfactory_tx_proto_depIdxs = nil
}
