// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package ics27_gmp

// Account discriminators
var (
	Account_Ics26RouterStateClient            = [8]byte{221, 237, 145, 143, 170, 194, 133, 115}
	Account_Ics26RouterStateClientSequence    = [8]byte{18, 97, 143, 135, 107, 101, 53, 226}
	Account_Ics26RouterStateIbcApp            = [8]byte{204, 125, 117, 159, 158, 163, 105, 66}
	Account_Ics26RouterStateRouterState       = [8]byte{141, 157, 194, 155, 75, 208, 200, 27}
	Account_Ics27GmpStateGmpAppState          = [8]byte{133, 28, 169, 125, 62, 118, 161, 140}
	Account_Ics27GmpStateGmpCallResultAccount = [8]byte{236, 115, 234, 143, 137, 175, 113, 32}
)

// Event discriminators
var (
	Event_Ics27GmpEventsAccessManagerUpdated  = [8]byte{115, 113, 220, 181, 221, 128, 58, 186}
	Event_Ics27GmpEventsGmpAppInitialized     = [8]byte{212, 236, 132, 161, 142, 153, 248, 176}
	Event_Ics27GmpEventsGmpAppPaused          = [8]byte{85, 230, 80, 71, 172, 103, 11, 186}
	Event_Ics27GmpEventsGmpAppUnpaused        = [8]byte{154, 224, 206, 7, 164, 216, 81, 181}
	Event_Ics27GmpEventsGmpCallAcknowledgment = [8]byte{239, 175, 112, 84, 147, 243, 239, 202}
	Event_Ics27GmpEventsGmpCallSent           = [8]byte{97, 205, 149, 75, 198, 28, 132, 141}
	Event_Ics27GmpEventsGmpCallTimeout        = [8]byte{10, 9, 192, 61, 183, 251, 100, 89}
	Event_Ics27GmpEventsGmpExecutionFailed    = [8]byte{78, 147, 179, 232, 5, 38, 127, 64}
)

// Instruction discriminators
var (
	Instruction_Initialize              = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_SendCall                = [8]byte{254, 95, 190, 68, 194, 140, 28, 103}
	Instruction_SendCallCpi             = [8]byte{97, 64, 45, 56, 8, 199, 98, 206}
	Instruction_OnRecvPacket            = [8]byte{153, 133, 78, 48, 156, 128, 229, 104}
	Instruction_OnAcknowledgementPacket = [8]byte{1, 142, 48, 169, 216, 66, 198, 31}
	Instruction_OnTimeoutPacket         = [8]byte{152, 10, 26, 185, 36, 193, 95, 76}
	Instruction_PauseApp                = [8]byte{142, 191, 211, 112, 238, 129, 131, 66}
	Instruction_UnpauseApp              = [8]byte{73, 253, 89, 192, 87, 42, 245, 3}
	Instruction_SetAccessManager        = [8]byte{95, 209, 134, 89, 195, 69, 35, 122}
)
