// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package ics27_gmp

// Account discriminators
var (
	Account_AccountState = [8]byte{168, 34, 15, 31, 235, 191, 144, 177}
	Account_GmpAppState  = [8]byte{133, 28, 169, 125, 62, 118, 161, 140}
)

// Event discriminators
var (
	Event_GmpAccountCreated           = [8]byte{122, 53, 243, 174, 243, 78, 190, 171}
	Event_GmpAcknowledgementProcessed = [8]byte{140, 142, 176, 159, 180, 217, 50, 73}
	Event_GmpAppInitialized           = [8]byte{212, 236, 132, 161, 142, 153, 248, 176}
	Event_GmpAppPaused                = [8]byte{85, 230, 80, 71, 172, 103, 11, 186}
	Event_GmpAppUnpaused              = [8]byte{154, 224, 206, 7, 164, 216, 81, 181}
	Event_GmpCallSent                 = [8]byte{97, 205, 149, 75, 198, 28, 132, 141}
	Event_GmpExecutionCompleted       = [8]byte{102, 200, 105, 241, 0, 238, 198, 16}
	Event_GmpExecutionFailed          = [8]byte{78, 147, 179, 232, 5, 38, 127, 64}
	Event_GmpTimeoutProcessed         = [8]byte{92, 151, 67, 120, 184, 236, 227, 78}
	Event_RouterCallerCreated         = [8]byte{37, 85, 180, 19, 123, 213, 153, 73}
)

// Instruction discriminators
var (
	Instruction_Initialize              = [8]byte{175, 175, 109, 31, 13, 152, 155, 237}
	Instruction_OnAcknowledgementPacket = [8]byte{1, 142, 48, 169, 216, 66, 198, 31}
	Instruction_OnRecvPacket            = [8]byte{153, 133, 78, 48, 156, 128, 229, 104}
	Instruction_OnTimeoutPacket         = [8]byte{152, 10, 26, 185, 36, 193, 95, 76}
	Instruction_PauseApp                = [8]byte{142, 191, 211, 112, 238, 129, 131, 66}
	Instruction_QueryAccountState       = [8]byte{123, 255, 49, 37, 104, 31, 54, 101}
	Instruction_SendCall                = [8]byte{254, 95, 190, 68, 194, 140, 28, 103}
	Instruction_UnpauseApp              = [8]byte{73, 253, 89, 192, 87, 42, 245, 3}
	Instruction_UpdateAuthority         = [8]byte{32, 46, 64, 28, 149, 75, 243, 88}
)
