// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package ics27_gmp

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_Ics27GmpEventsAccessManagerUpdated:
		value := new(Ics27GmpEventsAccessManagerUpdated)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as Ics27GmpEventsAccessManagerUpdated: %w", err)
		}
		return value, nil
	case Event_Ics27GmpEventsGmpAppInitialized:
		value := new(Ics27GmpEventsGmpAppInitialized)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as Ics27GmpEventsGmpAppInitialized: %w", err)
		}
		return value, nil
	case Event_Ics27GmpEventsGmpAppPaused:
		value := new(Ics27GmpEventsGmpAppPaused)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as Ics27GmpEventsGmpAppPaused: %w", err)
		}
		return value, nil
	case Event_Ics27GmpEventsGmpAppUnpaused:
		value := new(Ics27GmpEventsGmpAppUnpaused)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as Ics27GmpEventsGmpAppUnpaused: %w", err)
		}
		return value, nil
	case Event_Ics27GmpEventsGmpCallAcknowledgment:
		value := new(Ics27GmpEventsGmpCallAcknowledgment)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as Ics27GmpEventsGmpCallAcknowledgment: %w", err)
		}
		return value, nil
	case Event_Ics27GmpEventsGmpCallSent:
		value := new(Ics27GmpEventsGmpCallSent)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as Ics27GmpEventsGmpCallSent: %w", err)
		}
		return value, nil
	case Event_Ics27GmpEventsGmpCallTimeout:
		value := new(Ics27GmpEventsGmpCallTimeout)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as Ics27GmpEventsGmpCallTimeout: %w", err)
		}
		return value, nil
	case Event_Ics27GmpEventsGmpExecutionFailed:
		value := new(Ics27GmpEventsGmpExecutionFailed)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as Ics27GmpEventsGmpExecutionFailed: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_Ics27GmpEventsAccessManagerUpdated(eventData []byte) (*Ics27GmpEventsAccessManagerUpdated, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_Ics27GmpEventsAccessManagerUpdated {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_Ics27GmpEventsAccessManagerUpdated, binary.FormatDiscriminator(discriminator))
	}
	event := new(Ics27GmpEventsAccessManagerUpdated)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type Ics27GmpEventsAccessManagerUpdated: %w", err)
	}
	return event, nil
}

func ParseEvent_Ics27GmpEventsGmpAppInitialized(eventData []byte) (*Ics27GmpEventsGmpAppInitialized, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_Ics27GmpEventsGmpAppInitialized {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_Ics27GmpEventsGmpAppInitialized, binary.FormatDiscriminator(discriminator))
	}
	event := new(Ics27GmpEventsGmpAppInitialized)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type Ics27GmpEventsGmpAppInitialized: %w", err)
	}
	return event, nil
}

func ParseEvent_Ics27GmpEventsGmpAppPaused(eventData []byte) (*Ics27GmpEventsGmpAppPaused, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_Ics27GmpEventsGmpAppPaused {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_Ics27GmpEventsGmpAppPaused, binary.FormatDiscriminator(discriminator))
	}
	event := new(Ics27GmpEventsGmpAppPaused)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type Ics27GmpEventsGmpAppPaused: %w", err)
	}
	return event, nil
}

func ParseEvent_Ics27GmpEventsGmpAppUnpaused(eventData []byte) (*Ics27GmpEventsGmpAppUnpaused, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_Ics27GmpEventsGmpAppUnpaused {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_Ics27GmpEventsGmpAppUnpaused, binary.FormatDiscriminator(discriminator))
	}
	event := new(Ics27GmpEventsGmpAppUnpaused)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type Ics27GmpEventsGmpAppUnpaused: %w", err)
	}
	return event, nil
}

func ParseEvent_Ics27GmpEventsGmpCallAcknowledgment(eventData []byte) (*Ics27GmpEventsGmpCallAcknowledgment, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_Ics27GmpEventsGmpCallAcknowledgment {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_Ics27GmpEventsGmpCallAcknowledgment, binary.FormatDiscriminator(discriminator))
	}
	event := new(Ics27GmpEventsGmpCallAcknowledgment)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type Ics27GmpEventsGmpCallAcknowledgment: %w", err)
	}
	return event, nil
}

func ParseEvent_Ics27GmpEventsGmpCallSent(eventData []byte) (*Ics27GmpEventsGmpCallSent, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_Ics27GmpEventsGmpCallSent {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_Ics27GmpEventsGmpCallSent, binary.FormatDiscriminator(discriminator))
	}
	event := new(Ics27GmpEventsGmpCallSent)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type Ics27GmpEventsGmpCallSent: %w", err)
	}
	return event, nil
}

func ParseEvent_Ics27GmpEventsGmpCallTimeout(eventData []byte) (*Ics27GmpEventsGmpCallTimeout, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_Ics27GmpEventsGmpCallTimeout {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_Ics27GmpEventsGmpCallTimeout, binary.FormatDiscriminator(discriminator))
	}
	event := new(Ics27GmpEventsGmpCallTimeout)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type Ics27GmpEventsGmpCallTimeout: %w", err)
	}
	return event, nil
}

func ParseEvent_Ics27GmpEventsGmpExecutionFailed(eventData []byte) (*Ics27GmpEventsGmpExecutionFailed, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_Ics27GmpEventsGmpExecutionFailed {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_Ics27GmpEventsGmpExecutionFailed, binary.FormatDiscriminator(discriminator))
	}
	event := new(Ics27GmpEventsGmpExecutionFailed)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type Ics27GmpEventsGmpExecutionFailed: %w", err)
	}
	return event, nil
}
