// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package ics27_gmp

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("DFvpd9T9TNebBKDKiBkh6eQhoMhChzKSUwsMjBm9WPVK")
