// Code generated by tools/generate-pdas. DO NOT EDIT.
//
// This file is automatically generated from Anchor IDL files.
// Run 'just generate-pda' to regenerate.
//
// DO NOT EDIT THIS FILE MANUALLY.

package solana

import (
	"fmt"

	solanago "github.com/gagliardetto/solana-go"
)

type accessManagerPDAs struct{}
type attestationPDAs struct{}
type ics07TendermintPDAs struct{}
type ics26RouterPDAs struct{}
type ics27GmpPDAs struct{}
type iftPDAs struct{}
type mockLightClientPDAs struct{}
type testCpiTargetPDAs struct{}
type testGmpAppPDAs struct{}
type testIbcAppPDAs struct{}

var (
	AccessManager   = accessManagerPDAs{}
	Attestation     = attestationPDAs{}
	Ics07Tendermint = ics07TendermintPDAs{}
	Ics26Router     = ics26RouterPDAs{}
	Ics27Gmp        = ics27GmpPDAs{}
	Ift             = iftPDAs{}
	MockLightClient = mockLightClientPDAs{}
	TestCpiTarget   = testCpiTargetPDAs{}
	TestGmpApp      = testGmpAppPDAs{}
	TestIbcApp      = testIbcAppPDAs{}
)

func (accessManagerPDAs) AccessManagerPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("access_manager")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive AccessManager.AccessManagerPDA PDA: %v", err))
	}
	return pda, bump
}

func (accessManagerPDAs) ProgramDataPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte{0x36, 0x66, 0x8e, 0xef, 0x40, 0x96, 0x23, 0xb8, 0x3a, 0x37, 0xaf, 0x3e, 0xf6, 0xc8, 0x43, 0xfe, 0xeb, 0xb7, 0xbe, 0x8d, 0x42, 0xbd, 0x51, 0x30, 0x62, 0x54, 0x3b, 0x24, 0x92, 0xd1, 0x08, 0xaa}},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive AccessManager.ProgramDataPDA PDA: %v", err))
	}
	return pda, bump
}

func (accessManagerPDAs) ProgramDataWithAccountSeedPDA(programID solanago.PublicKey, program []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{program},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive AccessManager.ProgramDataWithAccountSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (accessManagerPDAs) UpgradeAuthorityWithArgSeedPDA(programID solanago.PublicKey, targetProgram []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("upgrade_authority"), targetProgram},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive AccessManager.UpgradeAuthorityWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (attestationPDAs) AppStatePDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("app_state")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Attestation.AppStatePDA PDA: %v", err))
	}
	return pda, bump
}

func (attestationPDAs) ClientPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("client")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Attestation.ClientPDA PDA: %v", err))
	}
	return pda, bump
}

func (attestationPDAs) ConsensusStateWithAccountSeedPDA(programID solanago.PublicKey, latestHeight []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("consensus_state"), latestHeight},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Attestation.ConsensusStateWithAccountSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (attestationPDAs) ConsensusStateWithArgSeedPDA(programID solanago.PublicKey, height []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("consensus_state"), height},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Attestation.ConsensusStateWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (attestationPDAs) ProgramDataPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte{0xd0, 0x56, 0x47, 0xd8, 0x4b, 0x8a, 0xa0, 0x59, 0x1a, 0x46, 0xb9, 0x27, 0x54, 0xe6, 0x18, 0x0d, 0x62, 0x4d, 0x87, 0x64, 0xc6, 0x77, 0xa5, 0x8e, 0xb4, 0x5d, 0xb8, 0x5e, 0x6e, 0xd1, 0xe4, 0xbb}},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Attestation.ProgramDataPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics07TendermintPDAs) AppStatePDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("app_state")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics07Tendermint.AppStatePDA PDA: %v", err))
	}
	return pda, bump
}

func (ics07TendermintPDAs) ClientPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("client")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics07Tendermint.ClientPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics07TendermintPDAs) ConsensusStateWithAccountSeedPDA(programID solanago.PublicKey, revisionHeight []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("consensus_state"), revisionHeight},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics07Tendermint.ConsensusStateWithAccountSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics07TendermintPDAs) ConsensusStateWithArgSeedPDA(programID solanago.PublicKey, revisionHeight []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("consensus_state"), revisionHeight},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics07Tendermint.ConsensusStateWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics07TendermintPDAs) ProgramDataPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte{0xfa, 0x20, 0x6e, 0xca, 0x52, 0x0c, 0xa6, 0xbf, 0x0a, 0x8f, 0x5e, 0xed, 0x96, 0xd3, 0x95, 0x03, 0x78, 0xd0, 0x6b, 0x55, 0x71, 0x5a, 0xe6, 0x44, 0xa3, 0xfd, 0xf4, 0x4d, 0x84, 0x09, 0x08, 0xec}},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics07Tendermint.ProgramDataPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics26RouterPDAs) ClientWithArgSeedPDA(programID solanago.PublicKey, sourceClient []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("client"), sourceClient},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics26Router.ClientWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics26RouterPDAs) CseqWithArgSeedPDA(programID solanago.PublicKey, sourceClient []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("cseq"), sourceClient},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics26Router.CseqWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics26RouterPDAs) IbcAppWithArgSeedPDA(programID solanago.PublicKey, portId []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("ibc_app"), portId},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics26Router.IbcAppWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics26RouterPDAs) PacketAckWithArgSeedPDA(programID solanago.PublicKey, destClient []byte, sequence []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("packet_ack"), destClient, sequence},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics26Router.PacketAckWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics26RouterPDAs) PacketCommitmentWithArgSeedPDA(programID solanago.PublicKey, sourceClient []byte, sequence []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("packet_commitment"), sourceClient, sequence},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics26Router.PacketCommitmentWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics26RouterPDAs) PacketReceiptWithArgSeedPDA(programID solanago.PublicKey, destClient []byte, sequence []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("packet_receipt"), destClient, sequence},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics26Router.PacketReceiptWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics26RouterPDAs) ProgramDataPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte{0xd6, 0x3a, 0xca, 0xc6, 0xab, 0xa1, 0x94, 0xbd, 0xd0, 0x13, 0x25, 0x9f, 0xa3, 0x2c, 0xb4, 0x68, 0xa6, 0xa9, 0x70, 0x33, 0x64, 0xff, 0x0c, 0xa7, 0xee, 0x9e, 0xe6, 0x47, 0x8d, 0xf0, 0x3c, 0xcd}},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics26Router.ProgramDataPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics26RouterPDAs) RouterStatePDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("router_state")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics26Router.RouterStatePDA PDA: %v", err))
	}
	return pda, bump
}

func (ics27GmpPDAs) AppStatePDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("app_state")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics27Gmp.AppStatePDA PDA: %v", err))
	}
	return pda, bump
}

func (ics27GmpPDAs) ClientWithArgSeedPDA(programID solanago.PublicKey, sourceClient []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("client"), sourceClient},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics27Gmp.ClientWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics27GmpPDAs) CseqWithArgSeedPDA(programID solanago.PublicKey, sourceClient []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("cseq"), sourceClient},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics27Gmp.CseqWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics27GmpPDAs) GmpResultWithArgSeedPDA(programID solanago.PublicKey, sourceClient []byte, sequence []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("gmp_result"), sourceClient, sequence},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics27Gmp.GmpResultWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics27GmpPDAs) IbcAppGmpportPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("ibc_app"), []byte("gmpport")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics27Gmp.IbcAppGmpportPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics27GmpPDAs) PacketCommitmentWithArgSeedPDA(programID solanago.PublicKey, sourceClient []byte, sequence []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("packet_commitment"), sourceClient, sequence},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics27Gmp.PacketCommitmentWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics27GmpPDAs) ProgramDataPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte{0x25, 0x28, 0x42, 0x7b, 0x8b, 0x00, 0x5b, 0x21, 0x2c, 0x37, 0xb4, 0xb0, 0xfd, 0x5e, 0x47, 0x71, 0x30, 0xe2, 0x61, 0xdb, 0xd4, 0xef, 0x22, 0xdb, 0x32, 0xf0, 0x48, 0xc1, 0x65, 0x40, 0xe5, 0x19}},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics27Gmp.ProgramDataPDA PDA: %v", err))
	}
	return pda, bump
}

func (ics27GmpPDAs) RouterStatePDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("router_state")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ics27Gmp.RouterStatePDA PDA: %v", err))
	}
	return pda, bump
}

func (iftPDAs) AppStatePDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("app_state")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ift.AppStatePDA PDA: %v", err))
	}
	return pda, bump
}

func (iftPDAs) GmpResultWithArgSeedPDA(programID solanago.PublicKey, clientId []byte, sequence []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("gmp_result"), clientId, sequence},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ift.GmpResultWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (iftPDAs) IftAppMintStateWithAccountSeedPDA(programID solanago.PublicKey, mint []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("ift_app_mint_state"), mint},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ift.IftAppMintStateWithAccountSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (iftPDAs) IftAppStatePDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("ift_app_state")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ift.IftAppStatePDA PDA: %v", err))
	}
	return pda, bump
}

func (iftPDAs) IftBridgeWithAccountSeedPDA(programID solanago.PublicKey, mint []byte, clientId []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("ift_bridge"), mint, clientId},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ift.IftBridgeWithAccountSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (iftPDAs) IftBridgeWithArgAndAccountSeedPDA(programID solanago.PublicKey, mint []byte, clientId []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("ift_bridge"), mint, clientId},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ift.IftBridgeWithArgAndAccountSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (iftPDAs) IftMintAuthorityWithAccountSeedPDA(programID solanago.PublicKey, mint []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("ift_mint_authority"), mint},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ift.IftMintAuthorityWithAccountSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (iftPDAs) PacketCommitmentWithArgSeedPDA(programID solanago.PublicKey, clientId []byte, sequence []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("packet_commitment"), clientId, sequence},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ift.PacketCommitmentWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (iftPDAs) PendingTransferWithArgAndAccountSeedPDA(programID solanago.PublicKey, mint []byte, clientId []byte, sequence []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("pending_transfer"), mint, clientId, sequence},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ift.PendingTransferWithArgAndAccountSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (iftPDAs) ProgramDataPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte{0xb8, 0x4f, 0x41, 0xf3, 0xa6, 0x2f, 0x4a, 0x01, 0x8f, 0x54, 0xa5, 0x49, 0x4f, 0xdf, 0x32, 0x3f, 0x96, 0xdb, 0xa0, 0xee, 0x5a, 0x7a, 0xfc, 0x0d, 0x96, 0x74, 0x18, 0xf9, 0xfe, 0x9d, 0x89, 0x1a}},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ift.ProgramDataPDA PDA: %v", err))
	}
	return pda, bump
}

func (iftPDAs) ReceiverTokenAccountWithAccountSeedPDA(programID solanago.PublicKey, receiverOwner []byte, tokenProgram []byte, mint []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{receiverOwner, tokenProgram, mint},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive Ift.ReceiverTokenAccountWithAccountSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (mockLightClientPDAs) ClientWithArgSeedPDA(programID solanago.PublicKey, chainId []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("client"), chainId},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive MockLightClient.ClientWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (mockLightClientPDAs) ConsensusStateWithArgSeedPDA(programID solanago.PublicKey, clientState []byte, latestHeight []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("consensus_state"), clientState, latestHeight},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive MockLightClient.ConsensusStateWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (testCpiTargetPDAs) CpiResultPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("cpi_result")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestCpiTarget.CpiResultPDA PDA: %v", err))
	}
	return pda, bump
}

func (testGmpAppPDAs) CounterAppStatePDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("counter_app_state")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestGmpApp.CounterAppStatePDA PDA: %v", err))
	}
	return pda, bump
}

func (testGmpAppPDAs) UserCounterWithAccountSeedPDA(programID solanago.PublicKey, userAuthority []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("user_counter"), userAuthority},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestGmpApp.UserCounterWithAccountSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (testGmpAppPDAs) UserCounterWithArgSeedPDA(programID solanago.PublicKey, user []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("user_counter"), user},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestGmpApp.UserCounterWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (testIbcAppPDAs) AppStatePDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("app_state")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestIbcApp.AppStatePDA PDA: %v", err))
	}
	return pda, bump
}

func (testIbcAppPDAs) ClientWithArgSeedPDA(programID solanago.PublicKey, sourceClient []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("client"), sourceClient},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestIbcApp.ClientWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (testIbcAppPDAs) CseqWithArgSeedPDA(programID solanago.PublicKey, sourceClient []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("cseq"), sourceClient},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestIbcApp.CseqWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (testIbcAppPDAs) EscrowStateWithArgSeedPDA(programID solanago.PublicKey, sourceClient []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("escrow_state"), sourceClient},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestIbcApp.EscrowStateWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (testIbcAppPDAs) EscrowWithArgSeedPDA(programID solanago.PublicKey, sourceClient []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("escrow"), sourceClient},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestIbcApp.EscrowWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (testIbcAppPDAs) IbcAppTransferPDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("ibc_app"), []byte("transfer")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestIbcApp.IbcAppTransferPDA PDA: %v", err))
	}
	return pda, bump
}

func (testIbcAppPDAs) IbcAppWithArgSeedPDA(programID solanago.PublicKey, sourcePort []byte) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("ibc_app"), sourcePort},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestIbcApp.IbcAppWithArgSeedPDA PDA: %v", err))
	}
	return pda, bump
}

func (testIbcAppPDAs) RouterStatePDA(programID solanago.PublicKey) (solanago.PublicKey, uint8) {
	pda, bump, err := solanago.FindProgramAddress(
		[][]byte{[]byte("router_state")},
		programID,
	)
	if err != nil {
		panic(fmt.Sprintf("failed to derive TestIbcApp.RouterStatePDA PDA: %v", err))
	}
	return pda, bump
}
