name: docker
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of the image to build'
        required: true
        type: string
  push:
    branches:
      - main
    tags:
      - relayer-v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '**.proto'
      - 'abi/**'

env:
  RELAYER_IMAGE: ghcr.io/cosmos/eureka-relayer
  GIT_TAG: "${{ inputs.tag }}"


# Cancel the workflow if a new commit is pushed to the branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-relayer-image:
    runs-on: depot-ubuntu-22.04-4
    permissions:
      id-token: write
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
    steps:
      - uses: actions/checkout@v4
        with:
         ref: "${{ inputs.tag || github.ref }}"
         fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          file: ./programs/relayer/Dockerfile
          outputs: type=image,"name=${{ env.RELAYER_IMAGE }}",push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.os }} # If we end up running more builds on the same OS, we need to differentiate more here
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1


  merge-relayer-image:
    runs-on: depot-ubuntu-22.04-4
    permissions:
      packages: write
      contents: read
    needs:
      - build-relayer-image
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Get docker tag
         # remove all `/` or `+` characters from the docker tag and replace them with a -.
         # this ensures the docker tag is valid.
        run: echo "DOCKER_TAG=$(echo $GIT_TAG | sed 's/[^a-zA-Z0-9\.]/-/g')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create --tag ${{ env.RELAYER_IMAGE }}:${{ env.DOCKER_TAG }} $(printf '${{ env.RELAYER_IMAGE }}@sha256:%s ' *)

